import { expect, test } from '@playwright/test'
import { PNG } from 'pngjs'

test('Innentueren und Zargen wechseln gemeinsam zwischen Eiche und Lackfarben', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  const result = await page.evaluate(async () => {
    const { buildScene } = await import('/src/scene.ts')
    const { finishes, initialSettings, exteriorStyles } = await import('/src/context.ts')
    const model = buildScene('EG', true, true, true)
    const doors = model.doors.filter(door => door.kind === 'door' && !door.id.endsWith('-entrance') && !door.object.material.transparent)
    const materials = new Set(doors.map(door => door.object.material))
    const frames = []
    model.group.traverse(object => { if (object.isMesh && object.name.endsWith('-frame') && materials.has(object.material)) frames.push(object) })
    const excluded = model.doors.filter(door => !doors.includes(door))
    const appearance = object => ({ color: object.material.color.getHexString(), map: !!object.material.map, transparent: object.material.transparent })
    const before = excluded.map(door => appearance(door.object))
    const defaults = doors.map(door => appearance(door.object))
    const samples = [...finishes.interiorDoor, finishes.interiorDoor[0]].map(finish => {
      for (const side of ['east', 'west']) model.setFinish('interiorDoor', finish.color, side)
      return { color: finish.color.slice(1), wood: finish === finishes.interiorDoor[0], doors: doors.map(door => appearance(door.object)), frames: frames.map(appearance) }
    })
    const style = exteriorStyles[0].appearance
    model.setFinish('interiorDoor', '#ffffff')
    for (const key of ['facade', 'roof', 'roofTrim', 'entryDoor', 'frame']) model.setFinish(key, style[key])
    model.setCladding(style.composition, style.woodTone, style.woodProfile)
    const afterStyle = doors.map(door => appearance(door.object))
    model.setFinish('entryDoor', initialSettings.entryDoor)
    model.setFinish('frame', initialSettings.frame)
    const after = excluded.map(door => appearance(door.object))
    const floors = [...new Set(doors.map(door => door.id.split('-')[0]))]
    model.dispose()
    return { defaults, samples, before, after, floors, frames: frames.length, afterStyle }
  })
  expect(result.floors.sort()).toEqual(['DG', 'EG', 'KG', 'OG'])
  expect(result.frames).toBeGreaterThan(10)
  expect(result.defaults.every(door => door.color === 'ffffff' && !door.map)).toBe(true)
  for (const sample of result.samples) {
    for (const material of [...sample.doors, ...sample.frames]) expect(material).toEqual({ color: sample.color, map: sample.wood, transparent: false })
  }
  expect(result.after).toEqual(result.before)
  expect(result.afterStyle.every(door => door.color === 'ffffff' && !door.map)).toBe(true)
  await page.getByRole('button', { name: '3D', exact: true }).click()
  const menu = page.locator('.scene-settings summary')
  await menu.click()
  for (const name of ['Reinweiß', 'Gebrochenes Weiß', 'Hellgrau', 'Eiche natur']) {
    const swatch = page.getByRole('button', { name: `Innentüren ${name}`, exact: true })
    await swatch.click()
    await expect(swatch).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByLabel('Außenstil', { exact: true })).toHaveValue('silver-terracotta')
  }
  await page.getByRole('button', { name: 'Innentüren Reinweiß', exact: true }).click()
  expect(await page.locator('.settings-body').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-interior-door-menu.png` })
  await page.getByLabel('Außenstil', { exact: true }).selectOption('bronze-slate')
  await expect(page.getByRole('button', { name: 'Innentüren Reinweiß', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await menu.click()
  await page.getByRole('button', { name: 'OG', exact: true }).click()
  await menu.click()
  await expect(page.getByRole('button', { name: 'Innentüren Reinweiß', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await menu.click()
  await page.getByRole('button', { name: '2D', exact: true }).click()
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await menu.click()
  await expect(page.getByRole('button', { name: 'Innentüren Reinweiß', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await menu.click()
  const image = PNG.sync.read(await page.locator('canvas').screenshot({ path: `test-results/${testInfo.project.name}-interior-doors-white.png` }))
  const colors = new Set<string>()
  for (let offset = 0; offset < image.data.length; offset += 16) colors.add(`${image.data[offset]},${image.data[offset + 1]},${image.data[offset + 2]}`)
  expect(colors.size).toBeGreaterThan(100)
  expect(errors).toEqual([])
})

test('Aussenstile setzen alle Oberflaechen pro Haus und bleiben individuell anpassbar', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  const probe = await page.evaluate(async () => {
    const { buildScene } = await import('/src/scene.ts')
    const { exteriorStyles, finishes, initialAppearance } = await import('/src/context.ts')
    const model = buildScene('EG', false, true, true)
    const west = model.group.getObjectByName('house-west')
    const color = mesh => mesh.material.color.getHexString()
    const snapshot = root => ({
      roof: root.getObjectByName('main-roof-panel').material.map(material => material.color.getHexString()),
      roofTrimMap: !!root.getObjectByName('main-roof-panel').material[0].map,
      door: color(root.getObjectByName('EG-entrance-leaf')),
      doorMap: !!root.getObjectByName('EG-entrance-leaf').material.map,
      frame: root.getObjectByName('EG-kitchen-east-window-mullion').material.map(material => material.color.getHexString()),
    })
    const westBefore = snapshot(west)
    const interiorDoor = model.doors.find(door => door.kind === 'door' && !door.id.startsWith('west-') && door.id !== 'EG-entrance' && !door.sliding && !door.object.material.transparent)
    const interiorBefore = color(interiorDoor.object)
    const apply = (appearance, side = 'east') => {
      for (const key of ['facade', 'roof', 'roofTrim', 'entryDoor', 'frame']) model.setFinish(key, appearance[key], side)
      model.setCladding(appearance.composition, appearance.woodTone, appearance.woodProfile, side)
    }
    apply(exteriorStyles[0].appearance)
    const cream = snapshot(model.group), westUnchanged = snapshot(west)
    const interiorAfter = color(interiorDoor.object)
    const interiorPlaster = color(model.group.getObjectByName('attic-ceiling'))
    apply(exteriorStyles.find(style => style.id === 'graphite-terracotta').appearance, 'west')
    const westDark = snapshot(west), eastUnchanged = snapshot(model.group)
    const samples = exteriorStyles.filter(style => style.id !== 'original').map(style => {
      apply(style.appearance)
      const labels = { facade: 'Fassade', roof: 'Dach', roofTrim: 'Dachunterbau', entryDoor: 'Haustür', frame: 'Fenster außen' }
      const swatches = Object.entries(labels).map(([key, label]) => `${label} ${finishes[key].find(finish => finish.color === style.appearance[key]).name}`)
      return { id: style.id, appearance: style.appearance, actual: snapshot(model.group), swatches }
    })
    apply(initialAppearance)
    const restored = snapshot(model.group)
    model.dispose()
    return { cream, westBefore, westUnchanged, westDark, eastUnchanged, restored, interiorBefore, interiorAfter, interiorPlaster, samples }
  })
  expect(probe.cream.roof).toEqual(['c4c7c4', ...Array(5).fill('424749')])
  expect(probe.cream.door).toBe('bcbdb7')
  expect(probe.cream.doorMap).toBe(false)
  expect(probe.cream.frame[0]).toBe('bcbdb7')
  expect(probe.cream.frame[1]).toBe('f7f7f4')
  expect(probe.westUnchanged).toEqual(probe.westBefore)
  expect(probe.eastUnchanged).toEqual(probe.cream)
  expect(probe.westDark.door).toBe('3b4243')
  expect(probe.westDark.roof[0]).toBe('3b4243')
  expect(probe.interiorAfter).toBe(probe.interiorBefore)
  expect(probe.interiorPlaster).toBe('ffffff')
  expect(probe.restored.doorMap).toBe(true)
  expect(probe.restored.door).toBe('dfd6c2')
  expect(probe.restored.roofTrimMap).toBe(false)
  for (const sample of probe.samples) {
    expect(sample.actual.roof).toEqual([sample.appearance.roofTrim.slice(1), ...Array(5).fill(sample.appearance.roof.slice(1))])
    expect(sample.actual.door).toBe(sample.appearance.entryDoor.slice(1))
    expect(sample.actual.frame[0]).toBe(sample.appearance.frame.slice(1))
    expect(sample.actual.frame[1]).toBe('f7f7f4')
    expect(sample.actual.roofTrimMap).toBe(sample.id === 'oak-terracotta')
  }
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await page.getByRole('button', { name: 'Dach', exact: true }).click()
  await expect(page.locator('.scene-settings')).toBeVisible()
  const menu = page.locator('.scene-settings summary')
  await menu.click()
  const style = page.getByLabel('Außenstil', { exact: true })
  await expect(style).toHaveValue('original')
  await page.getByRole('button', { name: 'Fassadenansicht', exact: true }).click()
  await menu.click()
  const canvas = page.locator('canvas')
  const before = PNG.sync.read(await canvas.screenshot())
  await menu.click()
  await style.selectOption('cream-grey')
  for (const name of ['Fassade Cremeweiß', 'Dach Graphit', 'Dachunterbau Hellgrau', 'Haustür Hellgrau', 'Fenster außen Hellgrau', 'Fenster innen Weiß']) {
    await expect(page.getByRole('button', { name, exact: true })).toHaveAttribute('aria-pressed', 'true')
  }
  await expect(page.getByLabel('Fassadenentwurf')).toHaveValue('plaster')
  await style.scrollIntoViewIfNeeded()
  expect(await page.locator('.settings-body').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-exterior-style-menu.png` })
  await menu.click()
  const after = PNG.sync.read(await canvas.screenshot({ path: `test-results/${testInfo.project.name}-exterior-style-cream.png` }))
  let changed = 0
  const colors = new Set<string>()
  for (let offset = 0; offset < after.data.length; offset += 4) {
    if (Math.abs(after.data[offset] - before.data[offset]) > 8) changed++
    colors.add(`${after.data[offset]},${after.data[offset + 1]},${after.data[offset + 2]}`)
  }
  expect(changed).toBeGreaterThan(500)
  expect(colors.size).toBeGreaterThan(100)
  const bounds = await canvas.boundingBox()
  await page.mouse.move(bounds!.x + bounds!.width * .5, bounds!.y + bounds!.height * .55)
  await page.mouse.down(); await page.mouse.move(bounds!.x + bounds!.width * .7, bounds!.y + bounds!.height * .55, { steps: 10 }); await page.mouse.up()
  const rotated = PNG.sync.read(await canvas.screenshot({ path: `test-results/${testInfo.project.name}-exterior-style-rotated.png` }))
  expect(Buffer.compare(after.data, rotated.data)).not.toBe(0)
  await menu.click()
  for (const sample of probe.samples) {
    await style.selectOption(sample.id)
    for (const name of sample.swatches) await expect(page.getByRole('button', { name, exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByLabel('Fassadenentwurf')).toHaveValue('plaster')
    await menu.click()
    await canvas.screenshot({ path: `test-results/${testInfo.project.name}-style-${sample.id}.png` })
    await menu.click()
  }
  await style.selectOption('cream-grey')
  await page.getByRole('button', { name: 'Fenster innen Moosgrün', exact: true }).click()
  await expect(style).toHaveValue('cream-grey')
  await page.getByRole('button', { name: 'Haustür Anthrazit', exact: true }).click()
  await expect(style).toHaveValue('custom')
  await style.selectOption('cream-grey')
  await expect(page.getByRole('button', { name: 'Fenster innen Moosgrün', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('Haushälfte', { exact: true }).selectOption('west')
  await expect(style).toHaveValue('original')
  await style.selectOption('oak-terracotta')
  await expect(page.getByRole('button', { name: 'Dachunterbau Eiche natur', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Fenster außen Eiche', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await style.selectOption('graphite-terracotta')
  await page.getByLabel('Haushälfte', { exact: true }).selectOption('east')
  await expect(style).toHaveValue('cream-grey')
  await menu.click()
  await page.getByRole('button', { name: '2D', exact: true }).click()
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await menu.click()
  await expect(style).toHaveValue('cream-grey')
  await page.getByLabel('Haushälfte', { exact: true }).selectOption('west')
  await expect(style).toHaveValue('graphite-terracotta')
  await style.selectOption('original')
  await expect(page.getByRole('button', { name: 'Haustür Eiche natur', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(errors).toEqual([])
})

test('Fensterfarben innen und außen bleiben je Haus unabhängig', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  const probe = await page.evaluate(async () => {
    const { buildScene } = await import('/src/scene.ts')
    const THREE = await import('/node_modules/.vite/deps/three.js')
    const model = buildScene('EG', false, true, true)
    const east = model.group.getObjectByName('EG-kitchen-east-window-mullion')
    const west = model.group.getObjectByName('house-west').getObjectByName('EG-kitchen-east-window-mullion')
    const colors = mesh => mesh.material.map(material => material.color.getHexString())
    const defaults = colors(east)
    model.setFinish('frameInside', '#ff0000')
    model.setFinish('frame', '#00ff00')
    model.setFinish('frameInside', '#0000ff', 'west')
    const eastColors = colors(east), westColors = colors(west)
    const normals = []
    for (const [id, normal] of [['EG-kitchen-east-window-secondary', [-1, 0, 0]], ['EG-garden-west-secondary', [0, 0, -1]], ['OG-bath-window-secondary', [0, 0, 1]]]) {
      const door = model.doors.find(door => door.id === id)
      const frame = door.pivot.children.find(mesh => mesh.userData.windowFrame)
      const face = frame.material.findIndex(material => material.color.getHexString() === 'ff0000')
      model.setOpening(id, 0); model.group.updateMatrixWorld(true)
      const direction = new THREE.Vector3(0, 0, face === 4 ? 1 : -1).transformDirection(frame.matrixWorld)
      model.setOpening(id, 1)
      normals.push({ actual: direction.toArray(), expected: normal, retained: colors(frame)[face] === 'ff0000' })
    }
    model.dispose()
    return { defaults, eastColors, westColors, normals }
  })
  expect(probe.defaults[0]).toBe('756f65')
  expect(probe.defaults[1]).toBe('f7f7f4')
  expect(probe.eastColors[0]).toBe('00ff00')
  expect(probe.eastColors[1]).toBe('ff0000')
  expect(probe.westColors[0]).toBe('756f65')
  expect(probe.westColors[1]).toBe('0000ff')
  for (const result of probe.normals) {
    result.actual.forEach((value, axis) => expect(value).toBeCloseTo(result.expected[axis]))
    expect(result.retained).toBe(true)
  }
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await expect(page.locator('.scene-settings')).toBeVisible()
  await page.locator('.scene-settings summary').click()
  await page.getByRole('button', { name: 'Fenster innen Moosgrün', exact: true }).click()
  await page.getByRole('button', { name: 'Fenster außen Weiß', exact: true }).click()
  await page.getByLabel('Haushälfte', { exact: true }).selectOption('west')
  await expect(page.getByRole('button', { name: 'Fenster innen Weiß', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('Haushälfte', { exact: true }).selectOption('east')
  expect(await page.locator('.settings-body').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-window-colors.png` })
  await page.locator('.scene-settings summary').click()
  await page.getByRole('button', { name: '2D', exact: true }).click()
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await page.locator('.scene-settings summary').click()
  await expect(page.getByRole('button', { name: 'Fenster innen Moosgrün', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Fenster außen Weiß', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.locator('.scene-settings summary').click()
  const image = PNG.sync.read(await page.locator('canvas').screenshot())
  const colors = new Set<string>()
  for (let offset = 0; offset < image.data.length; offset += 4) colors.add(`${image.data[offset]},${image.data[offset + 1]},${image.data[offset + 2]}`)
  expect(colors.size).toBeGreaterThan(100)
  expect(errors).toEqual([])
})

test('Fassaden: acht Kompositionen, Holztoene und Lamellen ohne Kamerasprung', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error' || (message.type() === 'warn' && message.text().startsWith('THREE.'))) errors.push(message.text()) })
  await page.goto('/')
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await page.getByRole('button', { name: 'Dach', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.__house?.snapshot().site)).toBe(true)
  const probe = await page.evaluate(async () => {
    const facadePath = '/src/facade.ts', scenePath = '/src/scene.ts', threePath = '/node_modules/.vite/deps/three.js'
    const { createFacadeMaterial } = await import(facadePath), { buildScene } = await import(scenePath), THREE = await import(threePath)
    const { house } = await import('/src/model.ts')
    const texture = new THREE.DataTexture(new Uint8Array([180, 120, 60, 255]), 1, 1); texture.needsUpdate = true
    const finish = createFacadeMaterial(texture), renderer = new THREE.WebGLRenderer(), target = new THREE.WebGLRenderTarget(8, 8)
    renderer.setSize(8, 8); renderer.setRenderTarget(target)
    const scene = new THREE.Scene(), camera = new THREE.OrthographicCamera(-.01, .01, .01, -.01, .01, 5)
    const geometry = new THREE.PlaneGeometry(.02, .02), mesh = new THREE.Mesh(geometry, finish.material)
    scene.add(mesh, new THREE.AmbientLight('#ffffff', 2))
    const sample = (x: number, y: number, z: number, mode: string, profile = 'boards') => {
      finish.setComposition(mode, 0, profile); mesh.position.set(x, y, z); camera.position.set(x, y, z + 1); camera.lookAt(x, y, z)
      renderer.render(scene, camera); const pixels = new Uint8Array(4); renderer.readRenderTargetPixels(target, 4, 4, 1, 1, pixels); return [...pixels]
    }
    const outerX = house.width - .1, innerX = house.east + .035
    const outer = sample(outerX, 3.5, 4.2, 'timber'), inner = sample(innerX, 3.5, 4.2, 'timber'), white = sample(innerX, 3.5, 4.2, 'plaster'), corner = sample(house.width - .3, 3.5, .1, 'timber'), gableReturn = sample(outerX, 7, 4.2, 'gable')
    const exteriorPlaster = sample(outerX, 7, 4.2, 'plaster'), og = sample(outerX, 3.5, 4.2, 'og'), dg = sample(outerX, 7, 4.2, 'og'), entry = sample(outerX, 1, 1.5, 'og-entry'), gap = sample(outerX, 3.5, 4.28, 'og', 'open-slats'), slat = sample(outerX, 3.5, 4.2, 'og', 'open-slats')
    const entrySurround = [[1, .2], [1, 1.8], [2.6, 1]].map(([height, south]) => sample(outerX, height, south, 'entry'))
    const outsideEntry = [[1, 2], [2.75, 1]].map(([height, south]) => sample(outerX, height, south, 'entry'))
    const { initialSettings } = await import('/src/context.ts')
    const model = buildScene('EG', false, true, false)
    const eastFrame = model.group.getObjectByName('EG-kitchen-east-window-mullion').material[0].color.getHexString()
    const westFrame = model.group.getObjectByName('house-west').getObjectByName('EG-kitchen-east-window-mullion').material[0].color.getHexString()
    const walls = model.group.children.filter((object: { name: string }) => object.name === 'EG-wall-east' || object.name === 'DG-wall-east').map((mesh: { name: string; material: { customProgramCacheKey: () => string }[] }) => ({ name: mesh.name, materials: mesh.material.map(material => material.customProgramCacheKey()) }))
    model.dispose(); geometry.dispose(); finish.material.dispose(); texture.dispose(); target.dispose(); renderer.dispose()
    return { outer, inner, white, corner, gableReturn, walls, og, dg, entry, gap, slat, exteriorPlaster, entrySurround, outsideEntry, eastFrame, westFrame, initialSettings }
  })
  expect(probe.inner).toEqual(probe.white)
  expect(probe.outer).not.toEqual(probe.white)
  expect(probe.corner).not.toEqual(probe.white)
  expect(probe.gableReturn).not.toEqual(probe.white)
  expect(probe.og).not.toEqual(probe.white)
  expect(probe.dg).toEqual(probe.exteriorPlaster)
  expect(probe.entry).not.toEqual(probe.white)
  for (const color of probe.entrySurround) expect(color).not.toEqual(probe.exteriorPlaster)
  for (const color of probe.outsideEntry) expect(color).toEqual(probe.exteriorPlaster)
  expect(probe.eastFrame).toBe('756f65')
  expect(probe.westFrame).toBe(probe.eastFrame)
  expect(probe.initialSettings.composition).toBe('entry')
  expect(probe.initialSettings.west.composition).toBe('entry')
  expect(probe.gap).toEqual(probe.exteriorPlaster)
  expect(probe.slat).not.toEqual(probe.white)
  expect(probe.walls.length).toBeGreaterThan(2)
  for (const wall of probe.walls) for (const [face, material] of wall.materials.entries()) expect(material.startsWith('facade-profiles-v4-room-bounce-')).toBe(face !== (wall.name.startsWith('DG') ? 4 : 1))
  await page.locator('.scene-settings summary').click()
  await page.getByRole('button', { name: 'Fassadenansicht', exact: true }).click()
  await page.getByLabel('Fassadenentwurf', { exact: true }).selectOption('plaster')
  await page.locator('.scene-settings summary').click()
  const camera = await page.evaluate(() => ({ ...window.__house!.position() }))
  const baseline = PNG.sync.read(await page.locator('canvas').screenshot())
  await page.screenshot({ path: `test-results/${testInfo.project.name}-facade-plaster.png` })
  for (const composition of ['timber', 'upper', 'gable', 'entry', 'og', 'og-entry', 'panels']) {
    await page.locator('.scene-settings summary').click()
    await page.getByLabel('Fassadenentwurf', { exact: true }).selectOption(composition)
    await page.locator('.scene-settings summary').click()
    const image = PNG.sync.read(await page.locator('canvas').screenshot())
    let changed = 0
    for (let offset = 0; offset < image.data.length; offset += 4) if (Math.abs(image.data[offset] - baseline.data[offset]) + Math.abs(image.data[offset + 1] - baseline.data[offset + 1]) > 12) changed++
    expect(changed / (image.width * image.height), composition).toBeGreaterThan(.0005)
    await page.screenshot({ path: `test-results/${testInfo.project.name}-facade-${composition}.png` })
    const position = await page.evaluate(() => ({ ...window.__house!.position() }))
    for (const axis of ['x', 'y', 'z'] as const) expect(position[axis]).toBeCloseTo(camera[axis], 8)
    expect(await page.evaluate(() => window.__house!.snapshot().slabs.every(slab => slab.colors[3] === 'ffffff'))).toBe(true)
  }
  await page.locator('.scene-settings summary').click()
  await page.getByLabel('Fassadenentwurf', { exact: true }).selectOption('upper')
  for (const tone of ['Silbergrau', 'Dunkel lasiert', 'Eiche hell', 'Thermoesche', 'Zeder', 'Gekälkt', 'Verkohlt']) {
    await page.getByRole('button', { name: `Holz ${tone}`, exact: true }).click()
    await expect(page.getByRole('button', { name: `Holz ${tone}`, exact: true })).toHaveAttribute('aria-pressed', 'true')
    await page.locator('.scene-settings summary').click()
    await page.screenshot({ path: `test-results/${testInfo.project.name}-facade-${tone.replace(' ', '-')}.png` })
    await page.locator('.scene-settings summary').click()
  }
  for (const profile of ['slats', 'open-slats']) {
    await page.getByLabel('Holzprofil', { exact: true }).selectOption(profile)
    await page.locator('.scene-settings summary').click()
    await page.screenshot({ path: `test-results/${testInfo.project.name}-facade-${profile}.png` })
    await page.locator('.scene-settings summary').click()
  }
  expect(await page.locator('.settings-body').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  expect(errors).toEqual([])
})