import { expect, test } from '@playwright/test'

test('Aussenanlagen: Masse, Auswahl, Massband, Zoom und SVG-Export', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Außenanlagen', exact: true }).click()
  const plan = page.getByRole('img', { name: 'Außenanlagenplan' })
  await expect(plan).toBeVisible()
  await expect(plan.locator('[data-site-object]')).toHaveCount(16)
  await expect(plan.locator('text').filter({ hasText: '3,25 m' })).toHaveCount(2)
  await expect(plan.locator('text').filter({ hasText: '2,50 m' })).toHaveCount(2)
  await expect(plan.locator('[data-site-object^="path-"] text').filter({ hasText: '0,90 m' })).toHaveCount(2)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-site-plan.png` })
  const carport = plan.locator('[data-site-object="carport-west"]')
  await carport.focus()
  expect(await carport.evaluate(element => getComputedStyle(element).outlineStyle)).toBe('none')
  expect(await carport.locator('polygon').evaluate(element => getComputedStyle(element).vectorEffect)).toBe('non-scaling-stroke')
  await page.screenshot({ path: `test-results/${testInfo.project.name}-site-focus.png` })
  await plan.locator('[data-site-object="bins-west"] > polygon').click()
  await expect(page.locator('.room-detail')).toContainText('2,25 m × 0,90 m')
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: 'Schließen', exact: true }).click()
  const initialView = await plan.getAttribute('viewBox')
  await page.getByRole('button', { name: 'Vergrößern', exact: true }).click()
  expect(await plan.getAttribute('viewBox')).not.toBe(initialView)
  await page.getByRole('button', { name: 'Ansicht zurücksetzen', exact: true }).click()
  await page.getByRole('button', { name: 'Maßband', exact: true }).click()
  const points = await plan.evaluate(element => {
    const matrix = (element as SVGSVGElement).getScreenCTM()!
    return [[0, 0], [7, 0]].map(([x, z]) => { const point = new DOMPoint(x, z).matrixTransform(matrix); return { x: point.x, y: point.y } })
  })
  for (const point of points) await page.mouse.click(point.x, point.y)
  await expect(plan.locator('[data-measurement="saved"]')).toHaveText('7,00 m')
  await page.getByRole('button', { name: 'Bemaßung', exact: true }).click()
  await expect(plan.locator('.site-dimension')).toHaveCount(0)
  await page.getByRole('button', { name: 'Bemaßung', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Plan herunterladen', exact: true }).click()
  expect((await downloadPromise).suggestedFilename()).toBe('Roeth10-Aussenanlagen.svg')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'EG', exact: true }).click()
  await expect(page.getByRole('img', { name: 'Grundriss Erdgeschoss' })).toBeVisible()
})