import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import { ArrowDownToLine, ArrowUpRight, Box, BrickWall, Footprints, Info, Layers2, Maximize, Minus, Plus, Ruler, Scissors, Sofa, Trees, X } from 'lucide-react'
import { area, construction, elevations, floorIds, format, house, makeFloor, ridgeElevations, roofOuterElevation, roofVerticalThickness, roomArea, stairOpeningParts, storeyRise } from './model'
import { metres } from './measure'
import type { FloorId } from './model'
import FloorPlan from './FloorPlan'
import SectionView from './SectionView'
import SitePlan from './SitePlan'
import SetbackDetails from './SetbackDetails'
import { siteItems } from './sitePlanModel'
import type { SiteItem } from './sitePlanModel'
import { initialSettings, siteArea } from './context'
import { terraceArea } from './terrace'
import './App.css'

const HouseScene = lazy(() => import('./HouseScene'))
export default function App() {
  const [floorId, setFloorId] = useState<FloorId>('EG')
  const [exterior, setExterior] = useState(false)
  const [siteItem, setSiteItem] = useState<SiteItem>(siteItems.find(item => item.id === 'carport-west')!)
  const [settings, setSettings] = useState(initialSettings)
  const [mode, setMode] = useState<'plan' | 'orbit' | 'walk'>('plan')
  const [selected, setSelected] = useState('living')
  const [dimensions, setDimensions] = useState(true)
  const [section, setSection] = useState(false)
  const [furnished, setFurnished] = useState(true)
  const [roof, setRoof] = useState(false)
  const [cutWalls, setCutWalls] = useState(false)
  const [zoom, setZoom] = useState(1)
  const [reset, setReset] = useState(0)
  const [info, setInfo] = useState(false)
  const [roomsOpen, setRoomsOpen] = useState(false)
  const canvasArea = useRef<HTMLDivElement>(null)
  useEffect(() => {
    if (mode !== 'plan') return
    const host = canvasArea.current!
    const wheel = (event: WheelEvent) => {
      if (!(event.target instanceof Element) || !event.target.closest('.floor-plan')) return
      event.preventDefault()
      const delta = event.deltaY * (event.deltaMode === 1 ? 16 : event.deltaMode === 2 ? host.clientHeight : 1)
      setZoom(value => Math.max(.7, Math.min(2.6, value * Math.exp(-delta * .0015))))
    }
    host.addEventListener('wheel', wheel, { passive: false })
    return () => host.removeEventListener('wheel', wheel)
  }, [mode])
  const floor = makeFloor(floorId)
  const activeRoom = floor.rooms.find(room => room.id === selected) ?? floor.rooms[0]
  const total = floor.rooms.reduce((sum, room) => sum + roomArea(room, floorId).floor, 0)
  const living = floor.rooms.reduce((sum, room) => sum + roomArea(room, floorId).living, 0)
  const changeFloor = (next: FloorId) => { setExterior(false); setFloorId(next); setSelected(next === 'EG' ? 'living' : next === 'DG' ? 'bedroom' : 'bath'); setZoom(1); setSettings(value => ({ ...value, transparentGround: next === 'KG' })) }
  const inspect = (id: string) => { setSelected(id); setRoomsOpen(false) }
  const download = () => {
    const svg = document.querySelector('.floor-plan')
    if (!svg) return
    const url = URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)], { type: 'image/svg+xml' }))
    const link = document.createElement('a'); link.href = url; link.download = `Hausentwurf-${exterior ? 'Aussenanlagen' : section ? 'Schnitt' : floorId}.svg`; link.click(); URL.revokeObjectURL(url)
  }
  return <div className="app">
    <header className="header"><div className="brand-mark"><Layers2 size={24} strokeWidth={1.6} /></div><div className="brand"><h1>Doppelhausentwurf <span>Ost</span></h1><p>DOPPELHAUSHÄLFTE · VORENTWURF</p></div><div className="project-state"><span className="status-dot" /> Vorentwurf <span className="revision">01</span></div><button className="icon-button" onClick={() => setInfo(true)} title="Planungsannahmen" aria-label="Planungsannahmen"><Info size={20} /></button></header>
    <div className="workspace">
      <aside className={`sidebar ${roomsOpen ? 'is-open' : ''}`}>
        {exterior ? <><div className="sidebar-heading"><span className="eyebrow">GRUNDSTÜCK</span><span className="small-index">OST + WEST</span></div><div className="floor-heading"><h2>Außenanlagen</h2></div><div className="level-metrics"><div><strong>{format(siteArea)}<small> m²</small></strong><span>Grundstück gesamt</span></div><div><strong>4</strong><span>Stellplätze</span></div></div><div className="room-list" aria-label="Außenobjekte">{siteItems.filter(item => !item.id.startsWith('approach') && !item.id.startsWith('access')).map(item => <button key={item.id} className={`room-row ${siteItem.id === item.id ? 'active' : ''}`} aria-pressed={siteItem.id === item.id} onClick={() => setSiteItem(item)}><span className="room-swatch" style={{ background: item.color }} /><span>{item.name}</span></button>)}</div><section className="room-detail" aria-live="polite"><div className="eyebrow">AUSSENMASSE</div><h3>{siteItem.name}</h3><p>{siteItem.details}</p>{siteItem.id.startsWith('carport') && <p>3,00 m Mindestabstand zur Südgrenze. Rückwand geschlossen; Tonnenfläche dahinter.</p>}{siteItem.id.startsWith('bins') && <p>Kompost, Restmüll, Papier: je eine schematische 240-l-Tonne, 60 × 75 cm. Bedienfläche davor 0,90 m tief.</p>}{siteItem.id.startsWith('open') && <p>5,00 m Stellplatzlänge plus mindestens 0,45 m Vorfläche zur schrägen Südgrenze.</p>}</section></> : <>
        <div className="sidebar-heading"><span className="eyebrow">ENTWURF</span><span className="small-index">01 / OST</span></div>
        <div className="variant-label">Hauptentwurf · U-Wendeltreppe</div>
        <div className="floor-heading"><h2>{floor.name}</h2><span>{floorId}</span></div>
        <div className="level-metrics"><div><strong>{format(total)}<small> m²</small></strong><span>Lichte Raumflächen</span></div><div><strong>{floorId === 'DG' ? '35°' : floor.height.toLocaleString('de-DE', { minimumFractionDigits: 2 })}<small>{floorId === 'DG' ? '' : ' m'}</small></strong><span>{floorId === 'DG' ? 'Dachneigung' : 'Lichte Höhe'}</span></div></div>
        <div className="room-list" aria-label="Räume">{floor.rooms.map((room, index) => <button key={room.id} className={`room-row ${activeRoom.id === room.id ? 'active' : ''}`} onClick={() => inspect(room.id)} aria-pressed={activeRoom.id === room.id}><span className="room-number">{String(index + 1).padStart(2, '0')}</span><span className="room-swatch" style={{ background: room.color }} /><span>{room.name}</span><strong>{format(roomArea(room, floorId).floor)}<small> m²</small></strong></button>)}</div>
        <section className="room-detail" aria-live="polite"><div className="eyebrow">RAUMDETAIL</div><h3>{activeRoom.name}</h3><p>{activeRoom.note}</p><dl><div><dt>Lichte Grundfläche</dt><dd>{format(roomArea(activeRoom, floorId).floor)} m²</dd></div>{floorId === 'DG' && <div><dt>Wohnfläche, überschlägig</dt><dd>{format(roomArea(activeRoom, floorId).living)} m²</dd></div>}{activeRoom.parts.length === 1 && <div><dt>Lichte Abmessungen</dt><dd>{format(activeRoom.parts[0].width)} × {format(activeRoom.parts[0].depth)} m</dd></div>}</dl><button className="text-button" onClick={() => { setMode('walk'); setReset(value => value + 1) }}><Footprints size={17} /> Raum betreten <ArrowUpRight size={16} /></button></section>
        <div className="sidebar-foot"><span className="material-dot" /> Eiche natur · Matte Oberflächen</div>
        </>}
        {exterior && (siteItem.id === 'house-east' || siteItem.id === 'house-west') && <SetbackDetails side={siteItem.id === 'house-east' ? 'east' : 'west'} />}
      </aside>
      <main className="drawing-area">
        <div className="toolbar"><nav className="floor-tabs" aria-label="Geschoss">{floorIds.map(id => <button key={id} aria-pressed={!exterior && floorId === id} onClick={() => changeFloor(id)}>{id}</button>)}<button aria-label="Außenanlagen" title="Außenanlagen" aria-pressed={exterior} onClick={() => { setExterior(true); setMode('plan'); setSection(false); setZoom(1) }}><Trees size={18} /></button></nav><div className="mode-tabs" aria-label="Ansicht"><button aria-pressed={mode === 'plan'} onClick={() => setMode('plan')}><Layers2 size={16} />2D</button><button aria-pressed={mode === 'orbit'} onClick={() => { setMode('orbit'); if (exterior) { setRoof(true); setSettings(value => ({ ...value, transparentGround: false })) } }}><Box size={16} />3D</button><button aria-label="Rundgang" aria-pressed={mode === 'walk'} onClick={() => setMode('walk')}><Footprints size={16} /><span>Rundgang</span></button></div></div>
        <div className="canvas-area" ref={canvasArea}><div className="drawing-title"><span className="eyebrow">{mode === 'plan' ? exterior ? 'AUSSENANLAGEN' : section ? 'GEBÄUDESCHNITT' : 'GRUNDRISS' : mode === 'orbit' ? 'RAUMMODELL' : 'AUGENHÖHE · 1,65 M'}</span><span>{exterior ? 'Grundstück Ost + West' : mode === 'plan' && section ? 'Alle Geschosse' : floor.name} <i>/</i> Hauptentwurf</span></div>
          {mode === 'plan' ? exterior ? <SitePlan key={reset} dimensions={dimensions} zoom={zoom} selected={siteItem.id} onSelect={item => { setSiteItem(item); setRoomsOpen(true) }} /> : section ? <SectionView key={reset} floorId={floorId} furnished={furnished} zoom={zoom} /> : <FloorPlan key={`${floorId}-${reset}`} floor={floor} selected={activeRoom.id} onSelect={inspect} dimensions={dimensions} furnished={furnished} zoom={zoom} /> : <Suspense fallback={<div className="loading">Raummodell wird aufgebaut…</div>}><HouseScene key={`${floorId}-${mode}-${furnished}-${roof}-${cutWalls}-${activeRoom.id}-${reset}`} floorId={floorId} mode={mode} furnished={furnished} roof={roof} cutWalls={cutWalls} selected={activeRoom.id} reset={reset} settings={settings} onSettings={setSettings} /></Suspense>}
          {mode === 'orbit' && !roof && <button className={`icon-button section-toggle ${cutWalls ? 'on' : ''}`} title={cutWalls ? 'Volle Wandhöhe anzeigen' : 'Wände auf 1,05 m schneiden'} aria-label="Wände schneiden" aria-pressed={cutWalls} onClick={() => setCutWalls(!cutWalls)}><BrickWall size={19} /></button>}
          {mode === 'plan' && !exterior && <button className={`icon-button section-toggle ${section ? 'on' : ''}`} title={section ? 'Zurück zum Grundriss' : 'Gebäudeschnitt öffnen'} aria-label="Querschnitt" aria-pressed={section} onClick={() => { setSection(!section); setZoom(1) }}>{section ? <Layers2 size={19} /> : <Scissors size={19} />}</button>}
          <div className="drawing-controls"><button className={`icon-button ${dimensions ? 'on' : ''}`} title="Bemaßung ein-/ausblenden" aria-label="Bemaßung" aria-pressed={dimensions} onClick={() => setDimensions(!dimensions)}><Ruler size={19} /></button><button className={`icon-button ${furnished ? 'on' : ''}`} title="Möblierung ein-/ausblenden" aria-label="Möblierung" aria-pressed={furnished} onClick={() => setFurnished(!furnished)}><Sofa size={19} /></button>{mode === 'orbit' && <button className={`icon-button ${roof ? 'on' : ''}`} title="Dach ein-/ausblenden" aria-label="Dach" aria-pressed={roof} onClick={() => setRoof(!roof)}><Layers2 size={19} /></button>}<span className="control-separator" />{mode === 'plan' && <><button className="icon-button" title="Vergrößern" aria-label="Vergrößern" onClick={() => setZoom(Math.min(zoom + .2, 2.6))}><Plus size={19} /></button><button className="icon-button" title="Verkleinern" aria-label="Verkleinern" onClick={() => setZoom(Math.max(zoom - .2, .7))}><Minus size={19} /></button></>}<button className="icon-button" title="Ansicht zurücksetzen" aria-label="Ansicht zurücksetzen" onClick={() => { setZoom(1); setReset(value => value + 1) }}><Maximize size={18} /></button>{mode === 'plan' && <button className="icon-button" title="Plan als SVG herunterladen" aria-label="Plan herunterladen" onClick={download}><ArrowDownToLine size={18} /></button>}</div>
        </div>
        <footer className="drawing-footer"><span>{exterior ? 'Außenanlagen · Ost + West' : <><b>7,00 × 10,00 m</b> Außenmaß</>}</span><span>{exterior ? `${format(siteArea)} m² Grundstück` : floorId === 'KG' ? 'Nutzkeller' : `${format(living)} m² Wohnfläche*`}</span><span className="footer-extra">{exterior ? 'Rekonstruierte Grenzen' : `Treppenöffnung ${format(area(stairOpeningParts))} m² separat`}</span><button onClick={() => setInfo(true)}>Vorentwurf · ungeprüft <Info size={14} /></button></footer>
      </main>
    </div>
    <button className="mobile-room-toggle" onClick={() => setRoomsOpen(!roomsOpen)}>{roomsOpen ? <X size={18} /> : <Layers2 size={18} />}{roomsOpen ? 'Schließen' : exterior ? 'Objekte & Maße' : 'Räume & Flächen'}</button>
    {info && <div className="modal-backdrop" onClick={() => setInfo(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Planungsannahmen" onClick={event => event.stopPropagation()}>
      <button className="icon-button modal-close" autoFocus aria-label="Schließen" onClick={() => setInfo(false)}><X size={20} /></button><span className="eyebrow">PLANUNGSANNAHMEN</span><h2>Ein Entwurf. Kein Bauplan.</h2>
      <p>Grundlage sind eure Angaben, kein vermessener Lageplan und kein geprüfter Bebauungsplan. Statik, Brand-/Schallschutz, Rettungswege, Baugrenzen und Vollgeschoss-Einstufung sind nicht nachgewiesen.</p>
      <dl><div><dt>Außenhülle je Ebene</dt><dd>7,00 × 10,00 m</dd></div><div><dt>Wände außen / innen / West</dt><dd>38 / 16 / 40 cm</dd></div><div><dt>EG / OG lichte Höhe</dt><dd>{metres(construction.clearHeight)}</dd></div><div><dt>Holzdecken EG/OG und OG/DG</dt><dd>{metres(construction.timberFloor)} gesamt</dd></div><div><dt>Kellerdecke / KG lichte Höhe</dt><dd>{metres(construction.basementCeiling)} / {metres(construction.basementClearHeight)}</dd></div><div><dt>FFB KG / EG / OG / DG</dt><dd>{metres(elevations.KG)} / ±0,00 / +3,00 / +6,00 m</dd></div><div><dt>Satteldach / lichtes Innenknie</dt><dd>{house.pitch}° / {metres(house.knee)}</dd></div><div><dt>Dachpaket normal / vertikal</dt><dd>{metres(construction.roofNormal)} / {metres(roofVerticalThickness)}</dd></div><div><dt>First innen / außen ab FFB EG</dt><dd>+{metres(ridgeElevations.inside)} / +{metres(ridgeElevations.outside)}</dd></div><div><dt>Gelände / Außenfirst darüber</dt><dd>{metres(construction.terrain)} / {metres(ridgeElevations.outside - construction.terrain)}</dd></div><div><dt>Treppe EG–OG–DG</dt><dd>16 × {format(storeyRise('EG') / 16 * 100)} cm / 25 cm gerade</dd></div><div><dt>Treppe KG–EG</dt><dd>16 × {format(storeyRise('KG') / 16 * 100)} cm / 25 cm gerade</dd></div><div><dt>Terrasse, separat</dt><dd>{format(terraceArea)} m² inkl. Eckstück</dd></div><div><dt>Gemeinsames Grundstück</dt><dd>{format(siteArea)} m², rekonstruiert</dd></div><div><dt>Je Grundstückshälfte</dt><dd>{format(siteArea / 2)} m²</dd></div><div><dt>Grenzen N / O / S / W</dt><dd>20,5 / 25,5 / 28,1 / 25,5 m</dd></div><div><dt>Nachbarversatz nach Süden</dt><dd>1,20 m angenommen</dd></div></dl>
      <p><strong>Höhen sind Entwurfsannahmen, keine garantierten Fertighausmaße.</strong> 38 cm Außenwand einschließlich Fassade und Installationsebene; 35 cm Holzdecken einschließlich Fußboden und Unterdecke; 35 cm Dach einschließlich Innenverkleidung und Deckung. Die Einzelaufbauten müssen vom Hersteller innerhalb dieser Gesamtmaße bestätigt werden. 7 cm Firstzuschlag sind zusätzlich angenommen. KfW 40 ist durch diese Dicken nicht nachgewiesen. Die Kellerhülle verwendet schematisch dieselbe Außenkante; Beton, Dämmung, Abdichtung und das 30-cm-Boden-/Fundamentpaket sind unbemessen.</p>
      <p><strong>Abstandsflächen ungeprüft: 3 m sind keine Freigabe.</strong> Nach <a href="https://www.gesetze-bayern.de/Content/Document/BayBO-6" target="_blank" rel="noreferrer">Art. 6 BayBO</a> gilt grundsätzlich 0,4 H, mindestens 3 m; bei 35° wird an der Traufe ein Drittel der Dachhöhe hinzugerechnet. Mit ebenem Gelände bei {metres(construction.terrain)} ergibt das hier beispielhaft etwa {(Math.max(3, .4 * (roofOuterElevation(0) - construction.terrain + (ridgeElevations.outside - roofOuterElevation(0)) / 3))).toLocaleString('de-DE', { maximumFractionDigits: 2 })} m an der Traufe. Das ist kein Nachweis für dieses Grundstück. Giebelflächen, schräge Grenzen, Doppelhausanschluss und zulässige Überdeckungen sind gesondert zu prüfen. Maßgebliches Gelände, örtliche Satzungen, Bebauungsplan und verbindliche Hersteller-Schnitte müssen vor Festlegung des Hauses fachlich abgeglichen werden.</p>
      <p>7-m-Entwurf: 70 m² Bruttofläche je Ebene und Haushälfte, lichte Innenbreite {metres(house.east - house.west)}. Annähernd quadratische U-Wendeltreppe 2,10 × 2,20 m bei z=3,10 bis 5,30 m: 80 cm nördlich der Hausmitte. Vier gerade Nordstufen, acht Wendelstufen, drei Südstufen und Geschossaustritt, insgesamt 16 Steigungen. Gerade Auftritte 25 cm, letzte Trittfläche 50 cm; nominell 90 cm Laufbreite. Treppenöffnung {metres(area(stairOpeningParts))}². An die kompakte Herstellerreferenz angelehnter Vorentwurf, keine Ausführungsplanung. Radiale Innenkanten nur etwa 7,8 cm: Stufenverziehung, nutzbare Laufbreite, Kopffreiheit, Tragwerk und Brandschutz sind nicht nachgewiesen.</p>
      <p>EG: Dusch-WC 4,00 m², Dusche 90 × 90 cm im Südwesten direkt an Haustrennwand und Treppe. Die Duschbucht ist nur 90 cm breit. WC und Waschbecken im Norden, dort auch die 90-cm-Eingangstür mit innenliegendem Schwenkbereich. Rechts neben der Dusche offene Vorratsnische 120 × 99 cm, 1,19 m², mit 25 cm tiefem Regal und Zugang vom westlichen Durchgang. Keine abgeschlossene Speisekammer; Lüftung und Sanitärführung ungeprüft. Diele 6,87 m², Wohnen/Kochen/Essen 38,41 m². Östliche 180 cm der Küchenwand um 60 cm nach Süden versetzt, 16 cm starke Rücksprungwand. Haustür, Seitenlicht und Vordach unverändert. Deckengehoher Durchgang 1,30 m breit westlich der Küche, Küchenzugang von Süden. KG, OG, DG und Treppe unverändert.</p>
      <p>OG: Familienbad 11,7 m² mit 180 × 80 cm Wanne, 100 × 100 cm Dusche und 110-cm-Waschplatz. Kind Nordost 14,9 m², Kind Süd 14,0 m², jeweils mit Bett, Schreibtisch, eigenen Fenstern und 90-cm-Tür. Schrankbreiten 160 cm im Norden und 180 cm im Süden. Offene Leseecke 4,8 m² ohne eigenes Außenfenster, Flur 3,7 m². Kein Durchgangszimmer; Sanitärführung und Tageslicht ungeprüft.</p>
      <p>Die Zwischenwände und Einbauschränke der bisherigen Treppennische entfallen vollständig. Offenes Treppenauge ohne Bodenfüllung oberhalb des Kellers, mit Geländer am Flurrand. Beide EG-Treppenzugänge bleiben 90 cm breit und deckenhoch offen. Abstände, Podestflächen, Geländerausführung und Brandschutz sind fachlich zu prüfen.</p>
      <p>DG: Zimmertrennwand unter dem First bei z=5,00 m. Eltern/Ankleide 19,7 m² Bodenfläche, 16,7 m² höhengewichtet; Bett 180 × 200 cm. Westlich am Bett nur 43 cm, östlich 62 cm: eingeschränkter westlicher Bettzugang in dieser Testvariante. Gäste/Arbeit 14,4 m², 11,3 m² höhengewichtet, mit 140 × 200 cm Gästebett und Schreibtisch. Unabhängige Zugänge vom 2,1-m²-Verteiler. Zwei Dachfenster je 114 × 140 cm, zwei Ostgiebelfenster je 98 × 118 cm; kein Treppenhaus-Dachfenster. Traufstreifen bleiben ausgeschlossen. Belichtung und Aufenthaltsraum-Eignung ungeprüft.</p>
      <p>Küche: zwei Nord-Süd-Zeilen ab z=2,55 m. Mittig zwei 60-cm-Hochschränke für Kühlschrank und Backofen mit Front nach Osten, dahinter 120 cm lange, 16 cm starke Rückwand. Ab z=3,75 m niedrige Kochhalbinsel 180 × 86 cm ohne hohe Rückwand, mit zwei 90-cm-Auszügen und 20 cm tiefen rückseitigen Fächern. 80-cm-Kochfeld, südlich davon 92 cm freie Arbeitslänge. Ostzeile 300 × 60 cm mit Kaffeeplatz, 60-cm-Geschirrspüler, 80-cm-Spülenschrank und Arbeitsfläche. Arbeitsgang 120 cm, vor Hochschränken 130 cm; westlicher Durchgang 130 cm. Zum Esstisch 145 cm, bei zusätzlichen 60 cm Sitzbedarf am Nordende noch 85 cm. Arbeitsplatten gesamt 3,35 m² statt 4,16 m² der verworfenen Quer-Küche; kein nachgewiesener Nettostauraumgewinn. Garderobe 176 × 56 cm in der 180 × 60 cm Eingangsnische, Front zur Diele; Sitzbank bleibt. Küchenzugang nur von Süden, längerer Weg vom Eingang zum Kühlschrank. Fronten und Geräte schematisch; 60-cm-Auszüge verengen den Arbeitsgang auf etwa 60 cm. Keine simulierten Schranköffnungen oder geprüfte gleichzeitige Bedienung. Einbaumaße, Kochfeldabstand zum Hochschrank, Lüftung und Anschlüsse ungeprüft. Terrasse unverändert 16,125 m²; Lichtschächte 100 × 50 cm.</p>
      <p>Haustüren öffnen nach innen. Zimmertüren öffnen überwiegend in die Räume; die Elternzimmertür schwenkt in den Verteiler. Türschwenkbereiche und Möbel sind geometrisch stichprobenartig geprüft, kein baurechtlicher Bewegungsflächennachweis. Im Keller bleiben freie Tanzfläche, Sitzbank, Snacktisch, Diskokugel und langsam wandernde bunte Lichtpunkte ohne Stroboskop. Deckenbefestigung, Elektroinstallation, Lüftung und zulässige Kellernutzung sind fachlich zu prüfen.</p>
      <p>Sideboard: 180 × 45 × 60 cm; weißes Regal: 212 × 40 × 212 cm. Bestandssofa: 250 cm lang, 80 cm normale Tiefe, 170 cm Gesamttiefe an der Recamiere. Essbank an der Ostwand, drei Stühle nur gegenüber. Eingang mit 35 × 210 cm Festverglasung und L-Vordach im gewählten Holzton: 120 cm Ausladung, 220 cm Länge, Unterkante 235 cm; nördliche Seitenwange. Tragwerk, Entwässerung und Anschlüsse ungeprüft.</p>
      <p>Grundstück nach Skizze und vier Seitenlängen rekonstruiert. Innenwinkel NW / NO / SO / SW etwa 107,52° / 89,77° / 87,82° / 74,89°. Vier Seitenlängen allein bestimmen kein eindeutiges Viereck; Richtungen und Winkel sind angenähert. Mittige flächengleiche Nord-Süd-Teilung bleibt unverändert. Beide Hauskörper werden von der gemeinsamen Wand aus schmaler; Nachbarn, Stellplätze und Grundstücksgrenzen bleiben an ihrem Ort. Kein vermessener Lageplan und kein baurechtlicher Abstandsflächennachweis; Dachüberstände und Vordach sind gesondert zu prüfen.</p>
      <p>Die Westhälfte spiegelt sämtliche Hausbauteile, Einrichtung und Öffnungen mit 1,20 m Südversatz; Oberflächen unabhängig. Haustrennwände und Dachanschluss konstruktiv ungeklärt. Nachbargrundflächen, Parzellengrenzen und geknickte Straßenkanten sind aus der Flurkarte auf die vier eigenen Grundstücksecken eingepasst. Die südliche Häuserreihe ist nach der Vogelperspektive in Fassadenfarbe und Dachhöhe differenziert. Zuordnung, Höhen und Details bleiben Bildschätzungen; die Einpassung kann außerhalb des Grundstücks verzerren. Kein Altbestand auf dem eigenen Grundstück. Zaun, Wege, Bäume und Trennhecke bleiben erhalten; Hecke nördlich und südlich der Häuser, 1,45 m hoch. Gartenobjekte ohne physikalische Kollision. Lichtschächte, Geländeanschlüsse, Abdichtung und Entwässerung ungeprüft.</p>
      <p>Sonnenstand für 49,593° N / 11,052° O, Ortszeit MEZ/MESZ an drei Vergleichstagen 2026. Glas lässt direktes Sonnenlicht durch; Rahmen und Laibungen werfen Schatten. Decken- und Podestleuchten mit Entfernungsabfall und Schatten; künstliche Lichtwirkung aus Leistungsgründen nur im betrachteten Geschoss, im Rundgang automatisch folgend. Raumweise angenähertes, schalterabhängiges Reflexionslicht hellt Decken und Wände auf. Indirektes Tageslicht wird zusätzlich aus Fensterfläche, Raumfläche und Fensterabstand geschätzt, unabhängig von den Lampenschaltern; Lichtschächte stark reduziert, fensterlose Räume ohne eigenen Anteil. Kein echter indirekter Lichttransport, keine berechnete diffuse Verschattung, Glastransmission oder Lichtbrechung. Globaler Modus als gleichmäßig helle Entwurfsansicht. Offene Geschossansichten erhalten zusätzlich Licht von oben. Schatten sind eine geometrische Vorschau mit angenäherten Nachbarn und kein Belichtungs- oder Luxnachweis. Die 2D-Darstellung bleibt ein festes Öffnungsschema; bewegliche Fenster und Türen werden in 3D dargestellt, feste Verglasungen bleiben fest.</p>
      <p>Holzfassaden: ab EG, OG/DG, nur OG ohne Dachgeschoss, OG plus Eingang, Ostgiebel, Eingang oder vertikale Felder. Profile als Materialstudie: 14-cm-Bretter, schmale Lamellen im 6-cm-Raster oder offene Lamellenfelder auf Putz im 16-cm-Raster. Acht Holztöne; keine Produktspezifikation. Fugen sind Shaderdarstellung ohne räumliche Lamellentiefe. Unterkonstruktion, Hinterlüftung, Anschlüsse, Brandschutz und zusätzliche Bauteildicke sind offen.</p>
      <p>* Überschlägige Flächen nach lichten Modellmaßen: unter 1 m Dachhöhe nicht, 1–2 m halb, ab 2 m voll. Treppe, Nutzkeller und Terrasse ausgeschlossen; freie Flurerschließung enthalten. Kein amtlicher WoFlV-Nachweis. Der Kniestock ist als lichte Höhe am inneren Dachansatz, das Dachpaket mit 35 cm normal zur Dachfläche angenommen. Raumflächen in den Erläuterungen sind gerundete Orientierungswerte; die Raumliste berechnet die aktuelle dickere Hülle. Kein Schacht vorgesehen oder abgezogen, Einbaumöbel mitgerechnet. Tragende Innenwände und Haustechnik sind nicht bemessen.</p>
    </section></div>}
  </div>
}