import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import { ArrowDownToLine, ArrowUpRight, Box, BrickWall, Footprints, Info, Layers2, Maximize, Minus, Plus, Ruler, Scissors, Sofa, Trees, X } from 'lucide-react'
import { area, floorIds, format, makeFloor, roomArea, stairOpeningParts } from './model'
import type { FloorId } from './model'
import FloorPlan from './FloorPlan'
import SectionView from './SectionView'
import SitePlan from './SitePlan'
import { siteItems } from './sitePlanModel'
import type { SiteItem } from './sitePlanModel'
import { initialSettings, siteArea } from './context'
import { terraceArea } from './terrace'
import './App.css'

const HouseScene = lazy(() => import('./HouseScene'))
export default function App() {
  const [floorId, setFloorId] = useState<FloorId>('EG')
  const [exterior, setExterior] = useState(false)
  const [siteItem, setSiteItem] = useState<SiteItem>(siteItems.find(item => item.id === 'carport-west')!)
  const [settings, setSettings] = useState(initialSettings)
  const [mode, setMode] = useState<'plan' | 'orbit' | 'walk'>('plan')
  const [selected, setSelected] = useState('living')
  const [dimensions, setDimensions] = useState(true)
  const [section, setSection] = useState(false)
  const [furnished, setFurnished] = useState(true)
  const [roof, setRoof] = useState(false)
  const [cutWalls, setCutWalls] = useState(false)
  const [zoom, setZoom] = useState(1)
  const [reset, setReset] = useState(0)
  const [info, setInfo] = useState(false)
  const [roomsOpen, setRoomsOpen] = useState(false)
  const canvasArea = useRef<HTMLDivElement>(null)
  useEffect(() => {
    if (mode !== 'plan') return
    const host = canvasArea.current!
    const wheel = (event: WheelEvent) => {
      if (!(event.target instanceof Element) || !event.target.closest('.floor-plan')) return
      event.preventDefault()
      const delta = event.deltaY * (event.deltaMode === 1 ? 16 : event.deltaMode === 2 ? host.clientHeight : 1)
      setZoom(value => Math.max(.7, Math.min(2.6, value * Math.exp(-delta * .0015))))
    }
    host.addEventListener('wheel', wheel, { passive: false })
    return () => host.removeEventListener('wheel', wheel)
  }, [mode])
  const floor = makeFloor(floorId)
  const activeRoom = floor.rooms.find(room => room.id === selected) ?? floor.rooms[0]
  const total = floor.rooms.reduce((sum, room) => sum + roomArea(room, floorId).floor, 0)
  const living = floor.rooms.reduce((sum, room) => sum + roomArea(room, floorId).living, 0)
  const changeFloor = (next: FloorId) => { setExterior(false); setFloorId(next); setSelected(next === 'EG' ? 'living' : next === 'DG' ? 'bedroom' : 'bath'); setZoom(1); setSettings(value => ({ ...value, transparentGround: next === 'KG' })) }
  const inspect = (id: string) => { setSelected(id); setRoomsOpen(false) }
  const download = () => {
    const svg = document.querySelector('.floor-plan')
    if (!svg) return
    const url = URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)], { type: 'image/svg+xml' }))
    const link = document.createElement('a'); link.href = url; link.download = `Roeth10-${exterior ? 'Aussenanlagen' : section ? 'Schnitt' : floorId}.svg`; link.click(); URL.revokeObjectURL(url)
  }
  return <div className="app">
    <header className="header"><div className="brand-mark"><Layers2 size={24} strokeWidth={1.6} /></div><div className="brand"><h1>An der Röth <span>10</span></h1><p>BUCKENHOF · DOPPELHAUSHÄLFTE OST</p></div><div className="project-state"><span className="status-dot" /> Vorentwurf <span className="revision">01</span></div><button className="icon-button" onClick={() => setInfo(true)} title="Planungsannahmen" aria-label="Planungsannahmen"><Info size={20} /></button></header>
    <div className="workspace">
      <aside className={`sidebar ${roomsOpen ? 'is-open' : ''}`}>
        {exterior ? <><div className="sidebar-heading"><span className="eyebrow">GRUNDSTÜCK</span><span className="small-index">OST + WEST</span></div><div className="floor-heading"><h2>Außenanlagen</h2></div><div className="level-metrics"><div><strong>{format(siteArea)}<small> m²</small></strong><span>Grundstück gesamt</span></div><div><strong>4</strong><span>Stellplätze</span></div></div><div className="room-list" aria-label="Außenobjekte">{siteItems.filter(item => !item.id.startsWith('approach') && !item.id.startsWith('access')).map(item => <button key={item.id} className={`room-row ${siteItem.id === item.id ? 'active' : ''}`} aria-pressed={siteItem.id === item.id} onClick={() => setSiteItem(item)}><span className="room-swatch" style={{ background: item.color }} /><span>{item.name}</span></button>)}</div><section className="room-detail" aria-live="polite"><div className="eyebrow">AUSSENMASSE</div><h3>{siteItem.name}</h3><p>{siteItem.details}</p>{siteItem.id.startsWith('carport') && <p>3,00 m Mindestabstand zur Südgrenze. Rückwand geschlossen; Tonnenfläche dahinter.</p>}{siteItem.id.startsWith('bins') && <p>Kompost, Restmüll, Papier: je eine schematische 240-l-Tonne, 60 × 75 cm. Bedienfläche davor 0,90 m tief.</p>}{siteItem.id.startsWith('open') && <p>5,00 m Stellplatzlänge plus mindestens 0,45 m Vorfläche zur schrägen Südgrenze.</p>}</section></> : <>
        <div className="sidebar-heading"><span className="eyebrow">ENTWURF</span><span className="small-index">01 / OST</span></div>
        <div className="variant-label">Hauptentwurf · Zweimal viertelgewendelt</div>
        <div className="floor-heading"><h2>{floor.name}</h2><span>{floorId}</span></div>
        <div className="level-metrics"><div><strong>{format(total)}<small> m²</small></strong><span>Lichte Raumflächen</span></div><div><strong>{floorId === 'DG' ? '35°' : floor.height.toLocaleString('de-DE', { minimumFractionDigits: 2 })}<small>{floorId === 'DG' ? '' : ' m'}</small></strong><span>{floorId === 'DG' ? 'Dachneigung' : 'Lichte Höhe'}</span></div></div>
        <div className="room-list" aria-label="Räume">{floor.rooms.map((room, index) => <button key={room.id} className={`room-row ${activeRoom.id === room.id ? 'active' : ''}`} onClick={() => inspect(room.id)} aria-pressed={activeRoom.id === room.id}><span className="room-number">{String(index + 1).padStart(2, '0')}</span><span className="room-swatch" style={{ background: room.color }} /><span>{room.name}</span><strong>{format(roomArea(room, floorId).floor)}<small> m²</small></strong></button>)}</div>
        <section className="room-detail" aria-live="polite"><div className="eyebrow">RAUMDETAIL</div><h3>{activeRoom.name}</h3><p>{activeRoom.note}</p><dl><div><dt>Lichte Grundfläche</dt><dd>{format(roomArea(activeRoom, floorId).floor)} m²</dd></div>{floorId === 'DG' && <div><dt>Wohnfläche, überschlägig</dt><dd>{format(roomArea(activeRoom, floorId).living)} m²</dd></div>}{activeRoom.parts.length === 1 && <div><dt>Lichte Abmessungen</dt><dd>{format(activeRoom.parts[0].width)} × {format(activeRoom.parts[0].depth)} m</dd></div>}</dl><button className="text-button" onClick={() => { setMode('walk'); setReset(value => value + 1) }}><Footprints size={17} /> Raum betreten <ArrowUpRight size={16} /></button></section>
        <div className="sidebar-foot"><span className="material-dot" /> Eiche natur · Matte Oberflächen</div>
        </>}
      </aside>
      <main className="drawing-area">
        <div className="toolbar"><nav className="floor-tabs" aria-label="Geschoss">{floorIds.map(id => <button key={id} aria-pressed={!exterior && floorId === id} onClick={() => changeFloor(id)}>{id}</button>)}<button aria-label="Außenanlagen" title="Außenanlagen" aria-pressed={exterior} onClick={() => { setExterior(true); setMode('plan'); setSection(false); setZoom(1) }}><Trees size={18} /></button></nav><div className="mode-tabs" aria-label="Ansicht"><button aria-pressed={mode === 'plan'} onClick={() => setMode('plan')}><Layers2 size={16} />2D</button><button aria-pressed={mode === 'orbit'} onClick={() => { setMode('orbit'); if (exterior) { setRoof(true); setSettings(value => ({ ...value, transparentGround: false })) } }}><Box size={16} />3D</button><button aria-label="Rundgang" aria-pressed={mode === 'walk'} onClick={() => setMode('walk')}><Footprints size={16} /><span>Rundgang</span></button></div></div>
        <div className="canvas-area" ref={canvasArea}><div className="drawing-title"><span className="eyebrow">{mode === 'plan' ? exterior ? 'AUSSENANLAGEN' : section ? 'GEBÄUDESCHNITT' : 'GRUNDRISS' : mode === 'orbit' ? 'RAUMMODELL' : 'AUGENHÖHE · 1,65 M'}</span><span>{exterior ? 'Grundstück Ost + West' : mode === 'plan' && section ? 'Alle Geschosse' : floor.name} <i>/</i> Hauptentwurf</span></div>
          {mode === 'plan' ? exterior ? <SitePlan key={reset} dimensions={dimensions} zoom={zoom} selected={siteItem.id} onSelect={item => { setSiteItem(item); setRoomsOpen(true) }} /> : section ? <SectionView key={reset} floorId={floorId} furnished={furnished} zoom={zoom} /> : <FloorPlan key={`${floorId}-${reset}`} floor={floor} selected={activeRoom.id} onSelect={inspect} dimensions={dimensions} furnished={furnished} zoom={zoom} /> : <Suspense fallback={<div className="loading">Raummodell wird aufgebaut…</div>}><HouseScene key={`${floorId}-${mode}-${furnished}-${roof}-${cutWalls}-${activeRoom.id}-${reset}`} floorId={floorId} mode={mode} furnished={furnished} roof={roof} cutWalls={cutWalls} selected={activeRoom.id} reset={reset} settings={settings} onSettings={setSettings} /></Suspense>}
          {mode === 'orbit' && !roof && <button className={`icon-button section-toggle ${cutWalls ? 'on' : ''}`} title={cutWalls ? 'Volle Wandhöhe anzeigen' : 'Wände auf 1,05 m schneiden'} aria-label="Wände schneiden" aria-pressed={cutWalls} onClick={() => setCutWalls(!cutWalls)}><BrickWall size={19} /></button>}
          {mode === 'plan' && !exterior && <button className={`icon-button section-toggle ${section ? 'on' : ''}`} title={section ? 'Zurück zum Grundriss' : 'Gebäudeschnitt öffnen'} aria-label="Querschnitt" aria-pressed={section} onClick={() => { setSection(!section); setZoom(1) }}>{section ? <Layers2 size={19} /> : <Scissors size={19} />}</button>}
          <div className="drawing-controls"><button className={`icon-button ${dimensions ? 'on' : ''}`} title="Bemaßung ein-/ausblenden" aria-label="Bemaßung" aria-pressed={dimensions} onClick={() => setDimensions(!dimensions)}><Ruler size={19} /></button><button className={`icon-button ${furnished ? 'on' : ''}`} title="Möblierung ein-/ausblenden" aria-label="Möblierung" aria-pressed={furnished} onClick={() => setFurnished(!furnished)}><Sofa size={19} /></button>{mode === 'orbit' && <button className={`icon-button ${roof ? 'on' : ''}`} title="Dach ein-/ausblenden" aria-label="Dach" aria-pressed={roof} onClick={() => setRoof(!roof)}><Layers2 size={19} /></button>}<span className="control-separator" />{mode === 'plan' && <><button className="icon-button" title="Vergrößern" aria-label="Vergrößern" onClick={() => setZoom(Math.min(zoom + .2, 2.6))}><Plus size={19} /></button><button className="icon-button" title="Verkleinern" aria-label="Verkleinern" onClick={() => setZoom(Math.max(zoom - .2, .7))}><Minus size={19} /></button></>}<button className="icon-button" title="Ansicht zurücksetzen" aria-label="Ansicht zurücksetzen" onClick={() => { setZoom(1); setReset(value => value + 1) }}><Maximize size={18} /></button>{mode === 'plan' && <button className="icon-button" title="Plan als SVG herunterladen" aria-label="Plan herunterladen" onClick={download}><ArrowDownToLine size={18} /></button>}</div>
        </div>
        <footer className="drawing-footer"><span>{exterior ? 'Außenanlagen · Ost + West' : <><b>7,00 × 10,00 m</b> Außenmaß</>}</span><span>{exterior ? `${format(siteArea)} m² Grundstück` : floorId === 'KG' ? 'Nutzkeller' : `${format(living)} m² Wohnfläche*`}</span><span className="footer-extra">{exterior ? 'Rekonstruierte Grenzen' : `Treppenöffnung ${format(area(stairOpeningParts))} m² separat`}</span><button onClick={() => setInfo(true)}>Vorentwurf · ungeprüft <Info size={14} /></button></footer>
      </main>
    </div>
    <button className="mobile-room-toggle" onClick={() => setRoomsOpen(!roomsOpen)}>{roomsOpen ? <X size={18} /> : <Layers2 size={18} />}{roomsOpen ? 'Schließen' : exterior ? 'Objekte & Maße' : 'Räume & Flächen'}</button>
    {info && <div className="modal-backdrop" onClick={() => setInfo(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Planungsannahmen" onClick={event => event.stopPropagation()}>
      <button className="icon-button modal-close" autoFocus aria-label="Schließen" onClick={() => setInfo(false)}><X size={20} /></button><span className="eyebrow">PLANUNGSANNAHMEN</span><h2>Ein Entwurf. Kein Bauplan.</h2>
      <p>Grundlage sind eure Angaben, kein vermessener Lageplan und kein geprüfter Bebauungsplan. Statik, Brand-/Schallschutz, Rettungswege, Baugrenzen und Vollgeschoss-Einstufung sind nicht nachgewiesen.</p>
      <dl><div><dt>Außenhülle je Ebene</dt><dd>7,00 × 10,00 m</dd></div><div><dt>Wände außen / innen / West</dt><dd>36,5 / 16 / 40 cm</dd></div><div><dt>EG / OG lichte Höhe</dt><dd>2,65 m</dd></div><div><dt>Deckenpaket / KG lichte Höhe</dt><dd>30 cm / 2,40 m</dd></div><div><dt>Satteldach, First Ost–West</dt><dd>35° / 0,50 m</dd></div><div><dt>Treppe EG–OG–DG</dt><dd>16 × 18,44 / 26 cm gerade</dd></div><div><dt>Treppe KG–EG</dt><dd>16 × 16,88 / 26 cm gerade</dd></div><div><dt>Terrasse, separat</dt><dd>{format(terraceArea)} m² inkl. Eckstück</dd></div><div><dt>Gemeinsames Grundstück</dt><dd>{format(siteArea)} m², rekonstruiert</dd></div><div><dt>Je Grundstückshälfte</dt><dd>{format(siteArea / 2)} m²</dd></div><div><dt>Grenzen N / O / S / W</dt><dd>20,5 / 25,5 / 28,1 / 25,5 m</dd></div><div><dt>Nachbarversatz nach Süden</dt><dd>1,20 m angenommen</dd></div></dl>
      <p>7-m-Entwurf: 70 m² Bruttofläche je Ebene und Haushälfte, lichte Innenbreite 6,235 m. Zwei Viertelwendelungen mit geradem Mittellauf; An- und Austritt nach Osten. Kern 1,88 × 3,18 m bei z=2,80 bis 5,98 m: gegenüber der vorigen Variante 26 cm breiter und 52 cm kürzer. Je zwei horizontale Endstufen à 34 cm, drei mittlere Stufen à 26 cm, acht Wendelstufen mit etwa 27,5 cm auf der angenommenen Lauflinie und der Geschossaustritt. Weiterhin 16 unveränderte Steigungen und nominell 100 cm Laufbreite. Die Zwischenwand rückt 68 cm nach Westen: eine 68 × 86 cm lichte Nische mit durchgehendem Boden statt ungenutztem Zwischenraum. Tatsächliche Treppenöffnung 5,176 m², kleiner als das umschreibende Rechteck. Radiale Innenkanten nur etwa 7,8 cm. Stufenverziehung, nutzbare Laufbreite, Kopffreiheit, Handläufe, Tragwerk und Brandschutz sind fachlich nicht nachgewiesen; keine Ausführungsvorlage.</p>
      <p>EG: Dusch-WC 5,0 m² und Diele 8,9 m² bleiben unverändert. Wohnen/Kochen/Essen wächst von 35,75 auf 36,39 m², netto rund 0,64 m². Der vollbreite südliche Bereich beginnt 52 cm früher; die neue Nische bringt rund 0,59 m² nutzbaren Boden. Bestandsmöbel bleiben unverkleinert. KG: Technik 7,1 m², Waschen/Lager 17,1 m², Kinderpartyraum 21,8 m², Flur einschließlich Nische 3,6 m². Konkrete Technikgeräte und Wartungsflächen sind noch fachlich abzustimmen.</p>
      <p>OG: Familienbad im Norden 7,6 m² bei 3,34 × 2,275 m, weiterhin mit Wanne 180 × 80 cm, Dusche 100 × 100 cm und 110-cm-Waschplatz. Kind Nordost 14,06 m², Kind Südost 14,02 m²; je Bett, 140-cm-Schreibtisch, 180-cm-Schrank, eigene Fenster und 90-cm-Tür. Der separate Lese-/Abstellraum wächst auf 9,3 m². Verteiler 3,9 m² einschließlich 0,59 m² Nische; reine durchgehende Fläche 3,31 m² bei 95 cm Breite. Für die Südost-Zimmertür reicht er 30 cm über das Treppenende hinaus. Kein Querflur oder Durchgang durch ein Kinderzimmer. Leitungsführung und Installationsflächen bleiben fachlich zu planen.</p>
      <p>DG: Eltern/Ankleide 21,0 m² Bodenfläche, überschlägig 17,9 m² höhengewichtet. Bett 180 × 200 cm am Ostgiebel und südwestliche Ankleidezone. Gäste/Arbeit 12,2 m² Bodenfläche, 9,2 m² höhengewichtet; Schlafsofa mit 140 × 200 cm Liegefläche im ausgezogenen Zustand dargestellt. Flur einschließlich Nische 2,4 m². Weiterhin drei Dachfenster: je Zimmer 114 × 140 cm, Treppe 78 × 118 cm; das Treppenfenster liegt seitlich versetzt über dem Lauf und nicht über der neuen Wand. Zwei Ostgiebelfenster je 98 × 118 cm. Geschlossene Traufstreifen bleiben aus den Raumflächen ausgeschlossen. Belichtung, Brandschutzabstände und Aufenthaltsraum-Eignung ungeprüft.</p>
      <p>Küche: 240 × 100 cm Halbinsel mit Induktion und Siebträger, kurze Spülenzeile und 2,55 m hohe Schränke. Geräte, Abluft/Umluft und Installationen sind schematisch. Terrasse unverändert 16,125 m², mit der Außenkante um 50 cm nach innen verschoben; Holzdielen 14,4 cm mit 6 mm Fugen. Lichtschacht-Außenmaße 100 × 50 cm. Anschlüsse, Belichtung und Nachbarabstand ungeprüft.</p>
      <p>Haustüren öffnen nach innen. Zimmertüren öffnen überwiegend in die Räume; die Elternzimmertür schwenkt in den Verteiler. Die Gästezimmertür öffnet wieder nach innen, damit die neue Nische erreichbar bleibt. Laufwege und Möbelfreiheit sind im Modell geprüft, nicht baurechtlich nachgewiesen. Im Keller bleiben freie Tanzfläche, Sitzbank, Snacktisch, Diskokugel und langsam wandernde bunte Lichtpunkte ohne Stroboskop. Sichere Deckenbefestigung, Elektroinstallation, Lüftung und zulässige Kellernutzung sind fachlich zu prüfen.</p>
      <p>Sideboard: 180 × 45 × 60 cm; weißes Regal: 212 × 40 × 212 cm. Bestandssofa: 250 cm lang, 80 cm normale Tiefe, 170 cm Gesamttiefe an der Recamiere. Essbank an der Ostwand, drei Stühle nur gegenüber. Eingang mit 35 × 210 cm Festverglasung und L-Vordach im gewählten Holzton: 120 cm Ausladung, 220 cm Länge, Unterkante 235 cm; nördliche Seitenwange. Tragwerk, Entwässerung und Anschlüsse ungeprüft.</p>
      <p>Grundstück nach Skizze und vier Seitenlängen rekonstruiert. Innenwinkel NW / NO / SO / SW etwa 107,52° / 89,77° / 87,82° / 74,89°. Vier Seitenlängen allein bestimmen kein eindeutiges Viereck; Richtungen und Winkel sind angenähert. Mittige flächengleiche Nord-Süd-Teilung bleibt unverändert. Beide Hauskörper werden von der gemeinsamen Wand aus schmaler; Nachbarn, Stellplätze und Grundstücksgrenzen bleiben an ihrem Ort. Kein vermessener Lageplan und kein baurechtlicher Abstandsflächennachweis; Dachüberstände und Vordach sind gesondert zu prüfen.</p>
      <p>Die Westhälfte spiegelt sämtliche Hausbauteile, Einrichtung und Öffnungen mit 1,20 m Südversatz; Oberflächen unabhängig. Haustrennwände und Dachanschluss konstruktiv ungeklärt. Nachbargrundflächen, Parzellengrenzen und geknickte Straßenkanten sind aus der Flurkarte auf die vier eigenen Grundstücksecken eingepasst. Die südliche Häuserreihe ist nach der Vogelperspektive in Fassadenfarbe und Dachhöhe differenziert. Zuordnung, Höhen und Details bleiben Bildschätzungen; die Einpassung kann außerhalb des Grundstücks verzerren. Kein Altbestand auf dem eigenen Grundstück. Zaun, Wege, Bäume und Trennhecke bleiben erhalten; Hecke nördlich und südlich der Häuser, 1,45 m hoch. Gartenobjekte ohne physikalische Kollision. Lichtschächte, Geländeanschlüsse, Abdichtung und Entwässerung ungeprüft.</p>
      <p>Sonnenstand für 49,593° N / 11,052° O, Ortszeit MEZ/MESZ an drei Vergleichstagen 2026. Glas lässt direktes Sonnenlicht durch; Rahmen und Laibungen werfen Schatten. Decken- und Podestleuchten mit Entfernungsabfall und Schatten; künstliche Lichtwirkung aus Leistungsgründen nur im betrachteten Geschoss, im Rundgang automatisch folgend. Raumweise angenähertes, schalterabhängiges Reflexionslicht hellt Decken und Wände auf. Indirektes Tageslicht wird zusätzlich aus Fensterfläche, Raumfläche und Fensterabstand geschätzt, unabhängig von den Lampenschaltern; Lichtschächte stark reduziert, fensterlose Räume ohne eigenen Anteil. Kein echter indirekter Lichttransport, keine berechnete diffuse Verschattung, Glastransmission oder Lichtbrechung. Globaler Modus als gleichmäßig helle Entwurfsansicht. Offene Geschossansichten erhalten zusätzlich Licht von oben. Schatten sind eine geometrische Vorschau mit angenäherten Nachbarn und kein Belichtungs- oder Luxnachweis. Die 2D-Darstellung bleibt ein festes Öffnungsschema; bewegliche Fenster und Türen werden in 3D dargestellt, feste Verglasungen bleiben fest.</p>
      <p>Holzfassaden: ab EG, OG/DG, nur OG ohne Dachgeschoss, OG plus Eingang, Ostgiebel, Eingang oder vertikale Felder. Profile als Materialstudie: 14-cm-Bretter, schmale Lamellen im 6-cm-Raster oder offene Lamellenfelder auf Putz im 16-cm-Raster. Acht Holztöne; keine Produktspezifikation. Fugen sind Shaderdarstellung ohne räumliche Lamellentiefe. Unterkonstruktion, Hinterlüftung, Anschlüsse, Brandschutz und zusätzliche Bauteildicke sind offen.</p>
      <p>* Überschlägige Flächen nach lichten Modellmaßen: unter 1 m Dachhöhe nicht, 1–2 m halb, ab 2 m voll. Treppe, Nutzkeller und Terrasse ausgeschlossen; freie Flurerschließung enthalten. Kein amtlicher WoFlV-Nachweis. Der Kniestock ist als lichte Höhe am inneren Dachansatz, das Dachpaket mit 25 cm angenommen. Kein Schacht vorgesehen oder abgezogen, Einbaumöbel mitgerechnet. Tragende Innenwände und Haustechnik sind nicht bemessen.</p>
    </section></div>}
  </div>
}