import { useState } from 'react'
import type { PointerEvent } from 'react'
import { Ruler, Trash2, X } from 'lucide-react'
import type { Floor, Furniture } from './model'
import { house, format, heightLine, lightWells, roofWindows, roomArea, stairFor, stairOpeningParts, stairSolids, storeyRise } from './model'
import { stairWalkingLine } from './winderStair'
import { contains, distance, metres, planObjects, snapPoint } from './measure'
import type { Measurable, PlanPoint } from './measure'
import { terraceArea, terraceFurniture, terraceMain, terraceOutline } from './terrace'
import { partyRoom } from './partyRoomData'
import { kitchenModules, moduleFront } from './kitchenStorage'

function Furnishing({ item }: { item: Furniture }) {
  const { x, z, width, depth, kind } = item
  if (kind === 'coat-rack') return <g data-furniture={item.id} data-coat-hooks="true" transform={`translate(${x} ${z})`} stroke="#68766e" strokeWidth=".018"><rect width={width} height=".025" fill="#d3bb94" />{Array.from({ length: 7 }, (_, index) => <path key={index} d={`M${.15 + index * (width - .3) / 6} .025 v${depth - .025} h.035`} fill="none" />)}</g>
  if (item.id === 'kitchen-upper') return <g data-furniture={item.id} transform={`translate(${x} ${z})`} fill="none" stroke="#527d74" strokeWidth=".018" strokeDasharray=".05 .025"><rect width={width} height={depth} />{[1, 2].map(panel => <path key={panel} d={`M${panel * width / 3} 0 V${depth}`} />)}</g>
  if (kind === 'espresso' && item.angle === Math.PI / 2) return <g transform={`translate(${x + width} ${z}) rotate(90)`}><Furnishing item={{ ...item, x: 0, z: 0, width: depth, depth: width, angle: 0 }} /></g>
  if (kind === 'espresso' && item.angle === Math.PI) return <g transform={`translate(${x + width} ${z + depth}) rotate(180)`}><Furnishing item={{ ...item, x: 0, z: 0, angle: 0 }} /></g>
  if ((kind === 'wc' || kind === 'sink') && item.angle === Math.PI / 2) return <g transform={`translate(${x + width} ${z}) rotate(90)`}><Furnishing item={{ ...item, x: 0, z: 0, width: depth, depth: width, angle: 0 }} /></g>
  if (kind === 'cabinet' && item.angle === -Math.PI) return <g transform={`translate(${x + width} ${z}) scale(-1 1)`}><Furnishing item={{ ...item, x: 0, z: 0, angle: Math.PI }} /></g>
  if (kind === 'bed' && item.angle === Math.PI / 2) return <g transform={`translate(${x + width} ${z}) rotate(90)`}><Furnishing item={{ ...item, x: 0, z: 0, width: depth, depth: width, angle: 0 }} /></g>
  if (kind === 'bed' && item.angle === Math.PI) return <g data-bed-head="south" transform={`translate(${x + width} ${z + depth}) rotate(180)`}><Furnishing item={{ ...item, x: 0, z: 0, angle: 0 }} /></g>
  if (kind === 'sofa' && item.angle === Math.PI / 2) return <g transform={`translate(${x + width} ${z}) rotate(90)`}><Furnishing item={{ ...item, x: 0, z: 0, width: depth, depth: width, angle: 0 }} /></g>
  if (kind === 'sofa' && item.angle === Math.PI) return <g data-sofa-back="south" transform={`translate(${x + width} ${z + depth}) rotate(180)`}><Furnishing item={{ ...item, x: 0, z: 0, angle: 0 }} /></g>
  return <g data-furniture={item.id} data-concealed-fittings={item.concealedFittings || undefined} transform={`translate(${x} ${z})`} stroke="#777d73" strokeWidth=".018" fill={item.color ?? (kitchenModules(item).length ? '#ebede7' : ['fridge', 'kitchen-tall'].includes(item.id) ? '#cfdcd5' : kind === 'cabinet' || kind === 'counter' ? '#d3bb94' : kind === 'plant' ? '#93a88b' : '#faf9f5')}>
    <rect width={width} height={depth} rx={['sofa', 'bed', 'bath', 'wc', 'chair'].includes(kind) ? .08 : .015} />
    {kind === 'chair' && (item.seatHeight ? <g data-barstool={item.id}><rect x=".055" y=".055" width={width - .11} height={depth - .11} rx=".06" fill="#c5b08b" /><path d={`M.06 ${depth / 2} H${width - .06}`} /></g> : <rect data-chair-back={item.id} x={item.angle && item.angle !== Math.PI && item.angle > 0 ? width - .065 : 0} y={item.angle === Math.PI ? depth - .065 : 0} width={item.angle && item.angle !== Math.PI ? .065 : width} height={item.angle && item.angle !== Math.PI ? depth : .065} fill="#b09a79" />)}
    {item.baseInset && <rect data-legroom={item.id} x={item.baseInset.west} y="0" width={width - item.baseInset.west} height={depth - item.baseInset.south} fill="none" strokeDasharray=".05 .025" />}
    {item.niche && <rect data-cabinet-niche={item.id} x=".025" y=".025" width={width - .05} height={depth - .025} fill="#edf0e8" strokeDasharray=".04 .025" />}
    {kind === 'bed' && <><path d={`M .04 .5 H ${width - .04}`} /><rect x=".09" y=".1" width={width > 1.3 ? width / 2 - .16 : width - .18} height=".3" rx=".04" />{width > 1.3 && <rect x={width / 2 + .04} y=".1" width={width / 2 - .16} height=".3" rx=".04" />}<rect x=".05" y=".6" width={width - .1} height={depth - .68} fill="#d4dcd2" rx=".03" /></>}
    {kind === 'sofa' && <><rect x=".09" y=".05" width={width - .18} height=".18" fill="#d0d7c9" /><path d={`M ${width / 3} .25 V ${depth - .08} M ${width * 2 / 3} .25 V ${depth - .08}`} /><rect x=".08" y=".32" width=".35" height=".35" rx=".05" fill="#b9c8b0" /></>}
    {(kind === 'sink' || kind === 'bath') && <rect x=".07" y=".07" width={width - .14} height={depth - .14} rx=".08" fill="#e0eeee" />}
    {kind === 'wc' && <ellipse cx={width / 2} cy={depth * .6} rx={width * .32} ry={depth * .27} fill="#f1f3ef" />}
    {kind === 'shower' && <><path d={`M0 0 L${width} ${depth} M${width} 0 L0 ${depth}`} stroke="#b9cccc" /><circle cx={width / 2} cy={depth / 2} r=".04" fill="#777d73" /></>}
    {item.concealedFittings && <g fill="#b9cccc"><rect x={width / 2 - .08} y="0" width=".16" height=".025" />{kind !== 'wc' && <path d={`M${width / 2} 0 V.2`} strokeWidth=".025" />}</g>}
    {kind === 'desk' && <rect x={width * .3} y={depth * .25} width={width * .45} height={depth * .45} fill="#687b7b" />}
    {kind === 'hob' && <g fill="#384441" stroke="#afbeb6"><rect width={width} height={depth} />{[width > depth ? .18 : .14, width - (width > depth ? .18 : .14)].flatMap(east => [width > depth ? .14 : .18, depth - (width > depth ? .14 : .18)].map(south => <circle key={`${east}-${south}`} cx={east} cy={south} r=".095" />))}</g>}
    {kind === 'espresso' && <g fill="#63726e"><rect x=".025" y=".025" width={width - .05} height={depth * .55} /><path d={`M${width / 2} ${depth * .5} V${depth}`} strokeWidth=".035" /></g>}
    {kind === 'cabinet' && <path d={item.id === 'wardrobe' && item.angle === Math.PI ? `M0 .025 H${width} M${width / 2} 0 V${depth}` : item.angle === Math.PI ? `M0 ${depth / 2} H${width} M${width - .03} 0 V${depth}` : `M${width / 2} 0 V${depth}`} stroke="#b09a79" />}
    {item.front && <path data-cabinet-front={item.front} d={item.front === 'north' ? `M.02 .025 H${width - .02}` : item.front === 'south' ? `M.02 ${depth - .025} H${width - .02}` : item.front === 'east' ? `M${width - .025} .02 V${depth - .02}` : `M.025 .02 V${depth - .02}`} strokeWidth=".035" />}
    {(item.id === 'fridge' || item.id.startsWith('kitchen-tall')) && <text data-tall-cabinet={item.id} x={width / 2} y={depth / 2 + .06} textAnchor="middle" fontSize=".2" fill="#334b41" stroke="none">H</text>}
    {kitchenModules(item).map(module => { const front = moduleFront(module); return <g key={module.id} data-kitchen-module={module.id} data-front={module.front} fill="none" stroke="#a68e6c" strokeWidth=".01"><rect x={module.x - x} y={module.z - z} width={module.width} height={module.depth} strokeDasharray=".04 .025" /><rect x={front.x - x} y={front.z - z} width={front.width} height={front.depth} fill="#a68e6c" />{module.use === 'dishwasher' && <path d={`M${module.x - x + .08} ${module.z - z + .1} h.4 v.4 h-.4 Z m.07 .12 h.26 m-.26 .13 h.26`} />}</g> })}
    {kind === 'bench' && (Math.abs(item.angle ?? 0) === Math.PI / 2 ? <rect data-bench-back={item.angle! < 0 ? 'north' : 'south'} x="0" y={item.angle! < 0 ? 0 : depth - .08} width={width} height=".08" fill="#9eae98" /> : <rect x={width - .08} y="0" width=".08" height={depth} fill="#9eae98" />)}
    {['fridge', 'kitchen-tall', 'pantry-cabinet'].includes(item.id) && !item.angle && <path data-tall-front="south" d={`M.02 ${depth - .025} H${width - .02}`} strokeWidth=".035" />}
    {kind === 'bookcase' && <path d={width > depth ? `M${width / 3} 0 V${depth} M${width * 2 / 3} 0 V${depth}` : `M0 ${depth / 3} H${width} M0 ${depth * 2 / 3} H${width}`} />}
    {kind === 'plant' && <><circle cx={width / 2} cy={depth / 2} r={width * .46} /><path d={`M0 0 L${width} ${depth} M0 ${depth} L${width} 0`} /></>}
    {item.id === 'toaster' ? <g stroke="#384441" strokeWidth=".025"><path d={`M.045 .075 H${width - .045} M.045 .145 H${width - .045}`} /></g> : item.id === 'sodastream' ? <g fill="#93b8b8"><rect x=".04" y=".025" width={width - .08} height=".06" /><circle cx={width / 2} cy=".17" r=".045" /></g> : item.id === 'cookit' ? <g fill="#bfcaca"><circle cx=".29" cy={depth / 2} r=".145" /><circle cx=".29" cy={depth / 2} r=".06" fill="#53675f" /><rect x=".025" y=".16" width=".06" height=".18" fill="#53675f" /></g> : kind === 'machine' && <circle cx={width / 2} cy={depth / 2} r={Math.min(width, depth) * .3} fill="#c5d1d1" />}
  </g>
}
export default function FloorPlan({ floor, selected, onSelect, dimensions, furnished, zoom }: { floor: Floor; selected: string; onSelect: (id: string) => void; dimensions: boolean; furnished: boolean; zoom: number }) {
  const [pan, setPan] = useState({ x: 0, y: 0 })
  const [drag, setDrag] = useState<{ x: number; y: number; startX: number; startY: number } | null>(null)
  const [measuring, setMeasuring] = useState(false)
  const [origin, setOrigin] = useState<PlanPoint | null>(null)
  const [cursor, setCursor] = useState<PlanPoint | null>(null)
  const [lines, setLines] = useState<{ start: PlanPoint; end: PlanPoint }[]>([])
  const [hover, setHover] = useState<{ object: Measurable; left: number; top: number } | null>(null)
  const objects = planObjects(floor, furnished)
  const location = (event: PointerEvent<SVGSVGElement>) => {
    const matrix = event.currentTarget.getScreenCTM()!
    const point = new DOMPoint(event.clientX, event.clientY).matrixTransform(matrix.inverse())
    return snapPoint({ x: point.x, z: point.y }, measuring ? objects : [], 8 / Math.hypot(matrix.a, matrix.b), origin ?? undefined, event.shiftKey)
  }
  const move = (event: PointerEvent<SVGSVGElement>) => {
    const point = location(event); setCursor(point)
    if (drag && zoom > 1 && !measuring) { const matrix = event.currentTarget.getScreenCTM()!; setPan({ x: drag.startX + (event.clientX - drag.x) / matrix.a, y: drag.startY + (event.clientY - drag.y) / matrix.d }); setHover(null); return }
    const object = objects.findLast(object => contains(object, point))
    setHover(!measuring && object ? { object, left: Math.max(8, Math.min(event.clientX + 16, window.innerWidth - 276)), top: Math.max(8, Math.min(event.clientY + 18, window.innerHeight - 126)) } : null)
  }
  const labels: Record<string, [number, number]> = Object.fromEntries(floor.rooms.map(room => [room.id, room.spawn]))
  const entrance = floor.walls.find(wall => wall.id === 'east')?.openings.find(opening => opening.id === 'entrance')
  const viewWidth = 10.2 / zoom, viewHeight = (house.depth + 2.6) / zoom
  const core = stairFor()
  const walkingLine = stairWalkingLine(storeyRise(floor.id))
  walkingLine[0][0] = core.x + core.width - .05
  walkingLine[walkingLine.length - 1][0] = core.x + core.width - .05
  const beyondPlanCut = (height: number) => floor.id === 'DG' ? height < storeyRise(floor.id) / 2 : height > storeyRise(floor.id) / 2
  const arrowEnd = walkingLine.at(-1)!, arrowBefore = walkingLine.at(-2)!
  const arrowAngle = Math.atan2(arrowEnd[2] - arrowBefore[2], arrowEnd[0] - arrowBefore[0]) * 180 / Math.PI
  return <><div className="measure-tools"><button className={`icon-button ${measuring ? 'on' : ''}`} aria-label="Maßband" title="Maßband: zwei Punkte setzen; Shift für waagerecht/senkrecht" aria-pressed={measuring} onClick={() => { setMeasuring(!measuring); setOrigin(null); setHover(null) }}><Ruler size={19} /></button><button className="icon-button" aria-label="Messungen löschen" title="Messungen löschen" disabled={!lines.length && !origin} onClick={() => { setLines([]); setOrigin(null) }}><Trash2 size={18} /></button>{origin && <button className="icon-button" aria-label="Messung abbrechen" title="Messung abbrechen (Escape)" onClick={() => setOrigin(null)}><X size={18} /></button>}</div><svg xmlns="http://www.w3.org/2000/svg" className="floor-plan" role="img" tabIndex={0} aria-label={`Grundriss ${floor.name}`} viewBox={`${house.width / 2 - viewWidth / 2 - (zoom === 1 ? 0 : pan.x)} ${house.depth / 2 - viewHeight / 2 - (zoom === 1 ? 0 : pan.y)} ${viewWidth} ${viewHeight}`} onPointerDown={event => {
    event.currentTarget.focus()
    if (measuring) { const point = location(event); setCursor(point); if (origin) { if (distance(origin, point) > .001) setLines([...lines, { start: origin, end: point }]); setOrigin(null) } else setOrigin(point); return }
    move(event)
    if (event.target === event.currentTarget) { event.currentTarget.setPointerCapture(event.pointerId); setDrag({ x: event.clientX, y: event.clientY, startX: pan.x, startY: pan.y }) }
  }} onClickCapture={event => { if (measuring) event.stopPropagation() }} onPointerMove={move} onPointerLeave={() => setHover(null)} onPointerUp={() => setDrag(null)} onPointerCancel={() => setDrag(null)} onKeyDown={event => { if (event.key === 'Escape') { setOrigin(null); setHover(null) } if (event.key === 'Delete') { setLines([]); setOrigin(null) } }} style={{ fontFamily: 'IBM Plex Sans, sans-serif', touchAction: 'none', cursor: measuring ? 'crosshair' : undefined }}>
    <defs><pattern id="terrace-plan" width=".15" height="3" patternUnits="userSpaceOnUse"><rect width=".144" height="3" fill="#c8ad80" /><path d="M.03 0 V3 M.09 0 V3" stroke="#b49c77" strokeWidth=".005" /></pattern><pattern id="closed-eaves" width=".18" height=".18" patternUnits="userSpaceOnUse"><rect width=".18" height=".18" fill="#e4e6e4" /><path d="M0 .18 L.18 0" stroke="#c5cbc6" strokeWidth=".018" /></pattern></defs>
    <rect x="-.22" y="0" width=".22" height={house.depth} fill="#c7cac4" /><text x="-.4" y="5" fontSize=".12" fill="#868b80" textAnchor="middle" transform="rotate(-90 -.4 5)">HAUSTRENNWAND · NACHBAR WEST</text>
    {floor.id === 'EG' && terraceArea > 0 && <g><polygon data-terrace="east" points={terraceOutline.map(point => point.join(',')).join(' ')} fill="url(#terrace-plan)" /><rect x={terraceMain.x} y="13" width={terraceMain.width} height=".28" fill="#c6d7bc" /><text x="5.75" y="12.65" textAnchor="middle" fontSize=".2" fill="#526452">Terrasse · {format(terraceArea)} m²</text>{furnished && terraceFurniture.map(item => <Furnishing key={item.id} item={item} />)}</g>}
    {floor.id === 'KG' && <g fill="#e2e7e3" stroke="#8b9b90" strokeWidth=".025">{lightWells.map(({x, z, width, depth}) => <g key={`${x}-${z}`}><rect data-light-well="true" x={x} y={z} width={width} height={depth} />{Array.from({ length: 7 }, (_, index) => <line key={index} x1={x} x2={x + width} y1={z + (index + 1) * depth / 8} y2={z + (index + 1) * depth / 8} />)}</g>)}</g>}
    <rect x="0" y="0" width={house.width} height={house.depth} fill="#fff" />
    {floor.id === 'DG' && floor.walls.filter(wall => wall.id.startsWith('knee-')).map(wall => { const start = wall.id === 'knee-north' ? house.north : wall.z + wall.depth; const end = wall.id === 'knee-north' ? wall.z : house.south; return <rect key={wall.id} data-closed-eaves="true" x={wall.x} y={start} width={wall.width} height={end - start} fill="url(#closed-eaves)" pointerEvents="none" /> })}
    {floor.rooms.map(room => <g key={room.id} onClick={() => onSelect(room.id)} style={{ cursor: 'pointer' }}>{room.parts.map((part, index) => part.footprint ? <polygon key={index} points={part.footprint.map(point => point.join(',')).join(' ')} fill={room.color} opacity={selected === room.id ? 1 : .65} /> : <rect key={index} x={part.x} y={part.z} width={part.width} height={part.depth} fill={room.color} opacity={selected === room.id ? 1 : .65} />)}</g>)}
    {floor.rooms.flatMap(room => (room.tileParts ?? []).map((part, index) => <rect key={`${room.id}-${index}`} data-entry-tiles="true" x={part.x} y={part.z} width={part.width} height={part.depth} fill="#e7e4d9" fillOpacity=".65" stroke="#bab8ac" strokeWidth=".012" pointerEvents="none" />))}
    <g data-stair="half-turn-winder">
      {stairOpeningParts.map((part, index) => <rect key={index} x={part.x} y={part.z} width={part.width} height={part.depth} fill="#f4f0e8" />)}
      {stairSolids(storeyRise(floor.id)).map(solid => { const hidden = beyondPlanCut(solid.bottom + solid.height); return <polygon key={solid.id} data-step={solid.id} data-hidden-step={hidden} points={solid.footprint!.map(point => point.join(',')).join(' ')} fill={hidden ? 'none' : '#e6d1af'} stroke="#aa9473" strokeWidth=".016" strokeDasharray={hidden ? '.09 .06' : undefined} opacity={hidden ? .4 : 1} /> })}
      {walkingLine.slice(1).map((point, index) => { const previous = walkingLine[index], hidden = beyondPlanCut((previous[1] + point[1]) / 2); return <line key={index} data-stair-direction={hidden ? 'hidden' : 'visible'} x1={previous[0]} y1={previous[2]} x2={point[0]} y2={point[2]} stroke="#746e61" strokeWidth=".025" strokeDasharray={hidden ? '.09 .06' : undefined} opacity={hidden ? .45 : 1} /> })}
      <circle data-stair-start="true" cx={walkingLine[0][0]} cy={walkingLine[0][2]} r=".065" fill="none" stroke="#746e61" strokeWidth=".025" />
      <path d="M-.18 -.1 L0 0 L-.18 .1" transform={`translate(${arrowEnd[0]} ${arrowEnd[2]}) rotate(${arrowAngle})`} fill="none" stroke="#746e61" strokeWidth=".025" opacity=".45" />
      {floor.id === 'DG' && <rect x={core.x + core.width} y={core.end - core.runWidth} width=".065" height={core.runWidth} fill="#777d73" />}
      {floor.id !== 'KG' && <rect data-stair-eye-guard="true" x={core.x + core.width} y={core.z + core.runWidth} width=".04" height={core.depth - 2 * core.runWidth} fill="#777d73" />}
      <text x={core.x + .72} y={core.z + core.depth / 2} textAnchor="middle" fontSize=".105" fill="#655f51">½</text>
      <text x={core.x + .6} y={core.z + .15} textAnchor="middle" fontSize=".13" fill="#655f51">{floor.id === 'DG' ? '↑ von OG' : '↑ ' + (floor.id === 'KG' ? 'EG' : floor.id === 'EG' ? 'OG' : 'DG')}</text>
    </g>
    {floor.walls.map(wall => <g key={wall.id}>{wall.footprint ? <polygon data-angled-wall={wall.id} points={wall.footprint.map(point => point.join(',')).join(' ')} fill={wall.openings.length ? '#f7f8f4' : '#647064'} stroke="#647064" strokeWidth=".012" /> : <rect x={wall.x} y={wall.z} width={wall.width} height={wall.depth} fill={['west', 'east', 'north', 'south'].includes(wall.id) ? '#424a43' : '#647064'} />}{(wall.footprint ? [] : wall.openings).map(opening => {
      const east = wall.x + (wall.axis === 'x' ? opening.start : 0), south = wall.z + (wall.axis === 'z' ? opening.start : 0)
      const jamb = opening.frame ?? 0, leafWidth = opening.width - 2 * jamb
      return <g key={opening.id} data-opening={opening.id} transform={`translate(${east} ${south}) ${wall.axis === 'z' ? 'rotate(90)' : ''}`}><rect x="0" y={wall.axis === 'z' ? -wall.width : 0} width={opening.width} height={wall.axis === 'z' ? wall.width : wall.depth} fill={opening.kind === 'window' ? '#dbe9e8' : '#f7f8f4'} />{!!jamb && [0, opening.width - jamb].map(start => <rect key={start} data-door-frame="true" x={start} y={wall.axis === 'z' ? -wall.width : 0} width={jamb} height={wall.axis === 'z' ? wall.width : wall.depth} fill="#a89b84" />)}{opening.kind === 'passage' ? null : opening.kind === 'window' ? <path d={`M0 ${wall.axis === 'z' ? -wall.width / 2 : wall.depth / 2} H${opening.width}`} stroke="#739d9e" strokeWidth=".025" /> : opening.id === 'terrace' ? <g data-sliding-pane="inner" stroke="#739d9e" strokeWidth=".025" fill="none"><path d={`M0 .06 H${opening.width * 2} M${opening.width} -.02 v.16 M.2 -.12 h.9 l-.15 -.08 m.15 .08 l-.15 .08`} /></g> : <g stroke="#7b8979" strokeWidth=".018" fill="none" transform={`${opening.hinge === 'end' ? `translate(${opening.width - jamb} 0) scale(-1 1)` : `translate(${jamb} 0)`} ${['store-north', 'parents-entry-south'].includes(wall.id) !== (opening.swing === 'reverse') ? 'scale(1 -1)' : ''}`}><path d={`M0 0 V${-leafWidth} A${leafWidth} ${leafWidth} 0 0 1 ${leafWidth} 0`} /></g>}</g>
    })}</g>)}
    {floor.walls.flatMap(wall => wall.openings.filter(opening => opening.kind === 'window' && opening.windowLayout?.columns === 2).map(opening => {
      const east = wall.x + (wall.axis === 'x' ? opening.start + opening.width / 2 - .03 : wall.width / 2 - .04)
      const south = wall.z + (wall.axis === 'z' ? opening.start + opening.width / 2 - .03 : wall.depth / 2 - .04)
      return <rect key={`${wall.id}-${opening.id}`} data-window-mullion={opening.id} x={east} y={south} width={wall.axis === 'x' ? .06 : .08} height={wall.axis === 'x' ? .08 : .06} fill="#739d9e" />
    }))}
    {furnished && <g pointerEvents="none">{floor.furniture.map(item => <Furnishing key={item.id} item={item} />)}</g>}
    {floor.id === 'DG' && <g pointerEvents="none">{[1, 2].flatMap(height => [heightLine(height), house.depth - heightLine(height)].map(south => <g key={`${height}-${south}`}><line x1={house.west} x2={house.east} y1={south} y2={south} stroke="#608c94" strokeDasharray=".09 .06" strokeWidth=".022" /><text x={house.width - .25} y={south + .04} fontSize=".13" fill="#60818c">{height} m</text></g>))}<line x1={house.west} x2={house.east} y1={house.depth / 2} y2={house.depth / 2} stroke="#a4aaa1" strokeWidth=".012" strokeDasharray=".25 .05" /></g>}
    {dimensions && floor.rooms.map(room => { const point = labels[room.id] ?? room.spawn; const compact = ['wc', 'entry', 'hall', 'pantry'].includes(room.id); const labelWidth = compact ? .82 : 1.9; return <g key={room.id} data-room-label={room.id} onClick={() => onSelect(room.id)} style={{ cursor: 'pointer' }}><rect x={point[0] - labelWidth / 2} y={point[1] - .25} width={labelWidth} height=".56" rx=".04" fill="#f9fbf6" opacity=".91" /><text x={point[0]} y={point[1] - .04} textAnchor="middle" fontSize={compact ? '.105' : '.145'} fontWeight="500" fill="#334b41">{room.name}</text><text x={point[0]} y={point[1] + .18} textAnchor="middle" fontSize=".155" fontWeight="600" fill="#294c40">{format(roomArea(room, floor.id).floor)} m²</text></g> })}
    {floor.id === 'EG' && entrance && <g data-entrance-marker="true" transform={`translate(0 ${entrance.start + entrance.width / 2})`} fill="#6a867a"><path d={`M${house.width + .8} 0 H${house.width + .1} l.18 -.1 m-.18 .1 l.18 .1`} stroke="#6a867a" strokeWidth=".025" /><text x={house.width + .45} y="-.25" textAnchor="middle" fontSize=".13">EINGANG</text></g>}
    {dimensions && <g stroke="#8a9588" strokeWidth=".014" fill="#667262"><path d={`M0 -.25 V-.85 M${house.width} -.25 V-.85 M0 -.65 H${house.width} M${house.width + .3} 0 H${house.width + .95} M${house.width + .3} ${house.depth} H${house.width + .95} M${house.width + .7} 0 V${house.depth}`} /><text x={house.width / 2} y="-.79" textAnchor="middle" fontSize=".2" stroke="none">{house.width.toLocaleString('de-DE', { minimumFractionDigits: 2 })} m</text><text x={house.width + 1} y={house.depth / 2} textAnchor="middle" fontSize=".2" stroke="none" transform={`rotate(90 ${house.width + 1} ${house.depth / 2})`}>{house.depth.toLocaleString('de-DE', { minimumFractionDigits: 2 })} m</text><path d={`M${house.west} ${house.depth + .35} v.35 M${house.east} ${house.depth + .35} v.35 M${house.west} ${house.depth + .55} H${house.east}`} /><text x={house.width / 2} y={house.depth + .48} fontSize=".14" textAnchor="middle" stroke="none">{(house.east - house.west).toLocaleString('de-DE', { minimumFractionDigits: 3 })} m lichte Breite</text></g>}
    {floor.id === 'KG' && furnished && floor.furniture.some(item => item.id === 'party-sofa') && <g data-party-room="true" pointerEvents="none"><circle cx={partyRoom.x} cy={partyRoom.z} r={partyRoom.radius} fill="#dce8e8" stroke="#697f85" strokeWidth=".025" /></g>}
    {floor.id === 'DG' && roofWindows.map(window => <rect key={window.id} x={window.x} y={window.z} width={window.width} height={window.depth} fill="#d6edee" fillOpacity=".35" stroke="#42858c" strokeDasharray=".06 .04" strokeWidth=".025" pointerEvents="none" />)}
    {hover && <g pointerEvents="none" stroke="#227d80" strokeWidth=".025" fill="none"><rect x={hover.object.x} y={hover.object.z} width={hover.object.width} height={hover.object.depth} /><path d={`M${hover.object.x} ${hover.object.z - .12} h${hover.object.width} M${hover.object.x - .12} ${hover.object.z} v${hover.object.depth}`} /><text x={hover.object.x + hover.object.width / 2} y={hover.object.z - .19} fill="#195c60" stroke="#fff" strokeWidth=".055" paintOrder="stroke" textAnchor="middle" fontSize=".16">{metres(hover.object.width)}</text><text x={hover.object.x - .2} y={hover.object.z + hover.object.depth / 2} fill="#195c60" stroke="#fff" strokeWidth=".055" paintOrder="stroke" textAnchor="end" fontSize=".16">{metres(hover.object.depth)}</text></g>}
    <g className="measurement-lines" pointerEvents="none">{[...lines, ...(origin && cursor ? [{ start: origin, end: cursor }] : [])].map(({start, end}, index) => <g key={index}><line x1={start.x} y1={start.z} x2={end.x} y2={end.z} stroke="#b44736" strokeWidth=".028" strokeDasharray={index === lines.length ? '.08 .04' : undefined} />{[start, end].map((point, pointIndex) => <circle key={pointIndex} cx={point.x} cy={point.z} r=".045" fill="#b44736" />)}<text data-measurement={index < lines.length ? 'saved' : 'preview'} x={(start.x + end.x) / 2} y={(start.z + end.z) / 2 - .12} fontSize=".19" textAnchor="middle" fill="#913b2d" stroke="#fff" strokeWidth=".075" paintOrder="stroke">{metres(distance(start, end))}</text></g>)}</g>
  </svg>{hover && <div className="measure-tooltip" role="tooltip" style={{left: hover.left, top: hover.top}}><strong>{hover.object.label}</strong><span>{metres(hover.object.width)} × {metres(hover.object.depth)}</span><span>{hover.object.details}</span></div>}</>
}