import { construction, elevations, floorIds, house, makeFloor, roomArea } from './model'
import { referenceAreas } from './providerPlan'
import './provider-details.css'

const number = (value: number) => value.toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
export default function ProviderDetails() {
  const totals = floorIds.flatMap(id => makeFloor(id).rooms.map(room => roomArea(room, id))).reduce((sum, room) => ({ floor: sum.floor + room.floor, living: sum.living + room.living }), { floor: 0, living: 0 })
  return <>
    <p>Variante nach der neuen EG-/OG-Skizze: je Haushälfte {number(house.width)} × {number(house.depth)} m Außenmaß, zusammen {number(2 * house.width)} m breit und durch 90 cm Versatz {number(house.depth + .9)} m tief. KG und DG entsprechend abgeleitet. Grundstücksteilung unverändert flächengleich; Westhälfte weiterhin nur als Baukörper.</p>
    <p>Abstandsprüfung erforderlich: An der unveränderten Grundstücksposition beträgt der senkrechte Abstand der nordwestlichen Ecke des Westhauses zur Nordgrenze nur etwa 2,98 m. Das Haus wurde nicht automatisch verschoben. Dach- und Abstandsflächen sind zusätzlich zu prüfen; keine baurechtliche Freigabe.</p>
    <dl><div><dt>Außenwand / Trennwand / Innenwand</dt><dd>30 / 30 / 12,5 cm, geschätzt</dd></div><div><dt>Lichte Höhe EG / OG</dt><dd>{number(construction.clearHeight)} m</dd></div><div><dt>KG lichte Höhe / Decke</dt><dd>{number(construction.basementClearHeight)} / {number(construction.basementCeiling)} m</dd></div><div><dt>Geschossdecken</dt><dd>{number(construction.timberFloor)} m</dd></div><div><dt>FFB KG / EG / OG / DG</dt><dd>{floorIds.map(id => number(elevations[id])).join(' / ')} m</dd></div><div><dt>Dachneigung / Innenknie</dt><dd>{house.pitch}° / {number(house.knee)} m</dd></div></dl>
    <p>Wandaufbauten, 24 cm Dachpaket normal zur Dachfläche und 20 cm Bodenplatte sind Annahmen. Die 30 cm breiten Außenwandsteine sind im Grundriss schematisch durch Fugen im 30-cm-Raster angedeutet; kein Verlege- oder Ausführungsplan. Der 24-cm-Wert im Schnitt bezeichnet die obere Kehlbalkendecke bei 2,77 m lichter DG-Höhe, nicht eindeutig die Dachstärke. Decke und Dachschrägen sind modelliert. Keine zusätzlichen Dachfenster angenommen.</p>
    <p>Spitzboden über der geschlossenen Kehlbalkendecke; DG-Innenwände enden an deren Unterkante bei 2,77 m. In der offenen Geschossansicht ist die Decke ausgeblendet. Innenleuchten vorerst entfernt. Die beiden südlichen Gartenbäume und die beiden nördlichen Kugelbäume am Grundstück sind entfernt; übrige Bepflanzung und Nachbarvegetation bleiben erhalten. Treppenaufstieg von Süd nach Nord, auch der DG-Grundrisspfeil zeigt diese Aufwärtsrichtung. Abstellraumtür in der Ostwand 73 × 160 cm, niedriger rechteckiger Flügel mit geprüftem Abstand zur Dachschräge über den Schwenkweg. Kein aufrechter Durchgang; der Rundgang hat derzeit keine Duckfunktion. Beschlag und Ausführung nicht fachlich nachgewiesen.</p>
    <p>Treppe auf allen Geschossen um 58,5 cm nach Norden verschoben: Kern von z = 3,50 bis 5,50 m. Treppenform und Höhen unverändert. Zentrale Querwände 20 cm, Küchenwand 15 cm als geometrische Annahmen; Tragwerk nicht nachgewiesen. Der kürzere Baukörper senkt bei unveränderter Dachneigung und Kniehöhe die geometrische Firsthöhe. Geschoss- und Raumhöhen bleiben unverändert.</p>
    <p>EG: Gästebad im Nordwesten, Eingang im Nordosten. Die geflieste Fläche direkt an der Haustür ist als Diele mit 6,67 m² separat ausgewiesen; ab dem vorhandenen Bodenwechsel folgt der Flur mit 5,21 m² und Holzboden. Neben der Dusche ein nischenfüllender, deckenhoher Putzmittelschrank. Nordseitig nur eine flache Leiste mit sieben Wandhaken, ohne Schrank darunter. Gegenüber ein deckenhoher Garderobenschrank, 210 cm lang und 60 cm tief; zur Eingangswand bleiben 105 cm frei. Keine schräge Trennung zum Wohnen; offener Übergang neben der unveränderten Küche. Südlich der Treppe bleibt ein kurzer gerader Wandstummel bis x = 2,65 m. Der Wohn-/Koch-/Essbereich umfasst nun 40,08 m² lichte Grundfläche.</p>
    <p>Küche mit fünf 63 cm breiten, 2,77 m hohen Hochschränken bis zur Decke. Backofen im dritten Modul, Kühlgerät im vierten; äußere Eckschränke mit oberen Fronten über den anschließenden Arbeitszeilen. Rechts offene Arbeitsnische von 92 bis 152 cm Höhe, seitlich an die östliche Platte angeschlossen. Toaster in der Nische und Wassersprudler rechts südlich der Spüle außerhalb des Fensterbereichs; Espresso und Cookit links. Keine Küchengeräte in der Diele. Arbeitsplatten 92 cm hoch, keine zusätzlichen Hängeschränke.</p>
    <p>Halbinsel mit 40 cm freiem südlichem und 35 cm westlichem Beinraum unter der Platte; Barhocker mit 65 cm Sitzhöhe. Blinde Eckbereiche ohne behauptete zugängliche Fronten, linke Eckfront ab 152 cm über den Geräten. Einzelne Schranköffnungen geometrisch geprüft, keine Freigabe gleichzeitiger Öffnungen. Toaster-Wärmeabstände, Lüftung, Beschläge, Anschlüsse und Ergonomie sind herstellerseitig zu prüfen; die offene Nische allein ist keine Betriebsfreigabe.</p>
    <p>Haustür 110 × 252 cm einschließlich 3-cm-Rahmen, nach innen öffnend und nordseitig angeschlagen; daneben ein 30 cm breites, türhohes Festglas-Seitenteil. Gesamtbreite der Eingangsanlage 140 cm. Normale Innentüren einschließlich neuem Kellerabschluss im EG: 86 × 211 cm einschließlich Zarge; Türblatt 80 × 208 cm. Keine Hersteller- oder Rohbaumaße. Niedrige DG-Abstellraumtür und Hebeschiebeanlage bleiben weitere Sonderfälle.</p>
    <p>OG: T-Bad nach Vorlage: mittige Waschtisch-Vorwand mit einem Becken und beidseitiger Ablage nach Osten, dahinter bodengleiche Dusche 96 x 126 cm im Nordwesten und WC im Südwesten an einer 15-cm-Installationswand (Durchgänge je 85 cm), Wanne 180 x 80 cm an der Ostwand. Kind Nord im Nordosten, Spielzimmer im Osten, L-förmiges Kind Süd und Abstellraum südlich der Treppe. Kinderzimmer mit Betten, Schreibtischen und Schränken eingerichtet; Spielzimmer mit niedrigem Regal und Tisch. KG behält Technik/Lager, Keller und Hobby; DG behält Büro, Schlafen/Ankleide und Abstellraum. Möbel und Trennwände an die neue Hülle angepasst.</p>
    <p>Kellerfenster 90 × 75 cm; östliches Fenster mit 1,20 m Abstand seiner Südkante zur südlichen Außenkante. Beide Lichtschächte im Grundriss 130 × 50 cm, mittig zum Fenster mit je 20 cm seitlichem Überstand. Schachtmaße aus der Zeichnung angenähert, nicht gesondert bemaßt; Tiefe, Entwässerung und Herstellerdetails bleiben zu prüfen.</p>
    <p>Neue Fensterordnung mit überwiegendem 30-cm-Raster: Ostfenster in EG, OG und DG jeweils 150 cm breit bei z = 3,30 und 5,70 m. Die südliche Achse rückt 60 cm nach Norden; Öffnungen und gespiegelte Teilungen stehen symmetrisch zum First. EG über Spüle und Insel weiterhin 150 × 120 cm mit 120 cm Brüstung. Beide OG-Ostfenster jetzt bodentief 150 × 240 cm, DG weiterhin 150 × 210 cm. Breite Fenster erhalten ein durchgehendes Festfeld und einen nominell 60 cm breiten Lüftungsbereich, bewegliches Blatt nach Rahmen und Fugen etwa 51 cm. Unterlicht nur unter dem Öffnungsflügel: OG-Ost und EG-Südwest 90 cm, DG 60 cm. Möbel bleiben unverändert; das Spielzimmerregal steht vor dem Festfeld. DG-Trennwand weiterhin bei z = 5,10 m und niedriger Büroschrank 120 cm breit. Festes Unterlicht allein ist kein Absturzsicherungsnachweis.</p>
    <p>Eckverglasung unverändert: EG-Ostfestglas ab z = 9,30 m, südliche Hebeschiebeanlage 2,80 m mit westlichem Schiebeflügel 1,25 m und östlichem Festfeld 1,55 m. Beide Glasflächen treffen sich am 8-cm-Eckprofil bei x = 6,75/z = 10,35 m, Höhe 252 cm. Keine Mauerecke unter dem Sturz; Tragwerk und Eckkopplung ungeprüft. Sitzbank teilweise vor dem Ostfestglas. Flurfenster jetzt quadratisch 90 × 90 cm mit 150 cm Brüstung; beide Südfenster von Kind Süd bleiben 180 × 150 cm mit 90 cm Brüstung. Nordlichtband im OG-Bad weiterhin 240 × 90 cm mit 150 cm Brüstung, EG-Bad 120 × 60 cm mit 180 cm Brüstung.</p>
    <p>Warmgraue Außenrahmen und gemeinsame Holzfassung um Haustür und Seitenteil an beiden Haushälften; Holzband 20 cm seitlich und 18 cm über der Eingangsanlage. Verglasung weiterhin in der Wandmitte zurückgesetzt. Kein Treppenlichtband in der Haustrennwand und keine konstruierten Raffstorekästen. Lüftungsflügel sind kein Rettungsfensternachweis; Rettungswege, Verglasung, Absturzsicherung, Tageslicht, Beschattung und Wärmebrücken sind fachlich zu planen.</p>
    <h3>Flächenabgleich</h3>
    <p>Breite Fenster mit außermittigem Pfosten und einem nach innen öffnenden Lüftungsflügel neben dem Festfeld. Die Südfenster im OG behalten ihre Brüstung. Teilungen und Profile sind Planungsannahmen; keine Dreh-Kipp-Funktion oder Herstellerfreigabe nachgewiesen.</p>
    <p>Die Referenzwerte stammen ausschließlich aus der neuen EG-/OG-Skizze. Für KG und DG liegen keine neuen beschrifteten Pläne vor. Insbesondere die EG-Diele weicht mit den übernommenen Wandstärken und der Garderobennische von der Vorlage ab; Flächen werden nicht künstlich auf deren Beschriftung gesetzt.</p>
    <p>Modell gesamt: {number(totals.floor)} m² lichte Grundfläche; {number(totals.living)} m² überschlägige Wohnfläche.</p>
    <table className="area-comparison"><thead><tr><th>Raum</th><th>Netto Modell / Vorlage</th><th>Wohnen Modell</th></tr></thead><tbody>{floorIds.flatMap(id => makeFloor(id).rooms.map(room => { const actual = roomArea(room, id), reference = referenceAreas[id]?.[room.id]; return <tr key={`${id}-${room.id}`}><th>{id} · {room.name}</th><td>{number(actual.floor)} / {reference === undefined ? '-' : number(reference)}</td><td>{number(actual.living)}</td></tr> }))}</tbody><tfoot>{floorIds.map(id => { const actual = makeFloor(id).rooms.map(room => roomArea(room, id)), reference = referenceAreas[id]; return <tr key={id}><th>Summe {id}</th><td>{number(actual.reduce((sum, room) => sum + room.floor, 0))} / {reference ? number(Object.values(reference).reduce((sum, value) => sum + value, 0)) : '-'}</td><td>{number(actual.reduce((sum, room) => sum + room.living, 0))}</td></tr> })}</tfoot></table>
    <p>Alle Flächen in m². Modellflächen entstehen aus den Raumkonturen, nicht aus den Angebotsbeschriftungen. Wohnfläche: 3 % pauschaler Abzug entsprechend der Tabelle; DG zusätzlich unter 1 m nicht, 1–2 m halb, ab 2 m voll. Türnischen nicht mitgerechnet. Kellerflur einschließlich Treppengrundfläche. Abweichungen insbesondere bei Fluren und Dachschrägen bleiben erkennbar; kein WoFlV-Nachweis.</p>
    <p>Sideboard 180 × 45 × 60 cm, Sofa 250 × 170 cm mit 80 cm normaler Tiefe, lange Seite im Süden und Chaiselongue im Westen. Die Sofagruppe ist 20 cm nach Norden versetzt und hält damit 20 cm Abstand zur inneren Südwandkante. Essstühle zur Tischplatte ausgerichtet; Regal auf 110 cm Breite angepasst. Küche mit Kühlschrank, erhöhtem Backofen, Geschirrspüler, Kochfeld, Espressomaschine, Toaster, SodaStream und Cookit. Bedienflächen und Anschlüsse sind nicht herstellerseitig geprüft.</p>
    <p>Treppe als räumliche Annäherung: 190 × 200 cm, 15 Steigungen, 30 cm gerade Auftritte und nominell 85 cm Laufbreite. 20 cm modellierte Treppenstärke. Radiale Wendelstufen, Geländer und Kopffreiheit benötigen Fachplanung; ein begehbares Kollisionsmodell ersetzt keinen Treppennachweis. Statik, Brand-/Schallschutz, Rettungswege, Abstandsflächen und Vollgeschoss-Einstufung sind nicht nachgewiesen. Grundstück, Nachbarschaft, Garten und Stellplätze bleiben aus dem bisherigen Modell erhalten; die Skizzenlage ist nicht vermessen.</p>
  </>
}