import { construction, elevations, floorIds, house, houseEnvelope, housePlacement, makeFloor, roomArea } from './model'
import { boundaryDistance, partnerEnvelope } from './context'
import { houseSetbacks } from './setbacks'
import { referenceAreas } from './providerPlan'
import './provider-details.css'

const number = (value: number) => value.toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
export default function ProviderDetails() {
  const envelope = houseEnvelope(), west = partnerEnvelope()
  const northDistance = boundaryDistance([west.x, west.z], 0), northRequired = houseSetbacks('west').faces.find(face => face.id === 'north')!.maximum
  const totals = floorIds.flatMap(id => makeFloor(id).rooms.map(room => roomArea(room, id))).reduce((sum, room) => ({ floor: sum.floor + room.floor, living: sum.living + room.living }), { floor: 0, living: 0 })
  return <>
    <p>Je Haushälfte {number(envelope.width)} × {number(envelope.depth)} m Außenmaß, zusammen {number(2 * envelope.width)} m breit und durch 90 cm Versatz {number(envelope.depth + .9)} m tief. Außenwände und Trennwandanteil je Hälfte 40 cm. Innenräume, Möbel und das lokale Fenster-Raster bleiben unverändert; die beiden Innenräume rücken durch die stärkere Trennwand jeweils 10 cm auseinander. Grundstücksteilung unverändert flächengleich; Westhälfte weiterhin nur als Baukörper.</p>
    <p>Doppelhaus um {number(housePlacement.z * 100)} cm nach Süden verschoben. Der senkrechte Abstand der nordwestlichen Ecke des Westhauses zur Nordgrenze beträgt etwa {number(northDistance)} m. Die überschlägige Nord-Abstandsfläche beträgt {number(northRequired)} m.{northDistance < northRequired && <> Sie ragt an der kritischsten Ecke noch etwa {number(northRequired - northDistance)} m über die Nordgrenze hinaus.</>} Dach- und Abstandsflächen sind fachlich zu prüfen; keine baurechtliche Freigabe.</p>
    <dl><div><dt>Außenwand / Trennwand je Hälfte / Innenwand</dt><dd>40 / 40 / 12,5 cm, geschätzt</dd></div><div><dt>Lichte Höhe EG / OG</dt><dd>{number(construction.clearHeight)} m</dd></div><div><dt>KG lichte Höhe / Decke</dt><dd>{number(construction.basementClearHeight)} / {number(construction.basementCeiling)} m</dd></div><div><dt>Geschossdecken</dt><dd>{number(construction.timberFloor)} m</dd></div><div><dt>FFB KG / EG / OG / DG</dt><dd>{floorIds.map(id => number(elevations[id])).join(' / ')} m</dd></div><div><dt>Dachneigung / Innenknie</dt><dd>{house.pitch}° / {number(house.knee)} m</dd></div></dl>
    <p>Wandaufbauten, 24 cm Dachpaket normal zur Dachfläche und 20 cm Bodenplatte sind Annahmen. Das 30-cm-Fensterraster bleibt erhalten, die grauen Mauerwerksrasterlinien sind ausgeblendet. Gesamtmaße liegen auf den tatsächlichen Außenkanten; lichte Breite 6,300 m unten und lichte Länge 9,900 m links jeweils zwischen den Innenkanten der Außenwände. Kein Verlege- oder Ausführungsplan. Der 24-cm-Wert im Schnitt bezeichnet die obere Kehlbalkendecke bei 2,77 m lichter DG-Höhe, nicht eindeutig die Dachstärke. Decke und Dachschrägen sind modelliert.</p>
    <p>Spitzboden über der geschlossenen Kehlbalkendecke; DG-Innenwände enden an deren Unterkante bei 2,77 m. In der offenen Geschossansicht ist die Decke ausgeblendet. Innenleuchten vorerst entfernt. Die beiden südlichen Gartenbäume und die beiden nördlichen Kugelbäume am Grundstück sind entfernt; übrige Bepflanzung und Nachbarvegetation bleiben erhalten. Treppenaufstieg von Süd nach Nord, auch der DG-Grundrisspfeil zeigt diese Aufwärtsrichtung. DG-Abstellraum samt Tür und Regal entfernt. Die südliche Abseitenwand verläuft durchgehend bei z = 9,00 m, bündig zur Wand hinter dem Bett. Die Fläche davor gehört zum Büro / Gästezimmer im Süden: 22,24 m² lichte Grundfläche, rund 3,45 m² mehr. Kommode an der südlichen Abseitenwand 120 cm hoch; Dachschräge begrenzt die Stehhöhe. Dahinter bleibt ein geschlossener Hohlraum, keine Nutzfläche.</p>
    <p>Treppe auf allen Geschossen um 58,5 cm nach Norden verschoben: Kern von z = 3,50 bis 5,50 m. Treppenform und Höhen unverändert. Handlauf in allen drei Treppenverbindungen außen entlang der Nord-, West- und Südseite statt an der Mittelwand, mit durchgehenden Eckanschlüssen. Achse 6 cm von der äußeren Stufenkante, Durchmesser 5 cm; Höhenführung unverändert. Mittelwand und Stufen bleiben erhalten. Befestigung und normgerechte Wandabstände fachlich prüfen. Zentrale Querwände 20 cm, Küchenwand 15 cm als geometrische Annahmen; Tragwerk nicht nachgewiesen. Der kürzere Baukörper senkt bei unveränderter Dachneigung und Kniehöhe die geometrische Firsthöhe. Geschoss- und Raumhöhen bleiben unverändert.</p>
    <p>EG: Gästebad im Nordwesten, Eingang im Nordosten. Diele und Flur behalten den bisherigen Bodenwechsel. Neben der Dusche bleibt der deckenhohe Putzmittelschrank; Wandhaken und Garderobe im Eingang bleiben unverändert. Die linke Küchen-Flurwand und der linke Küchenunterschrank entfallen. Südlich der Treppe bleibt der kurze Wandstummel bis x = 2,65 m. Der Wohn-/Koch-/Essbereich umfasst 40,18 m², der nun direkt angebundene Flur 5,57 m². Die Skizzenflächen sind grobe Vergleichswerte, keine maßgeblichen Zielwerte.</p>
    <p>Küche mit 3,21 m breiter Hochschrankzeile und fünf schematisch gleich breiten Modulen, weiterhin 60 cm tief und 2,77 m hoch. Backofen im dritten Modul, Kühlgerät im vierten. Rechte offene Arbeitsnische von 92 bis 152 cm Höhe mit Toaster und Wassersprudler; Espresso und Cookit stehen auf der östlichen Arbeitszeile. Keine Küchengeräte in der Diele. Arbeitsplatten 92 cm hoch, keine zusätzlichen Hängeschränke. Modulbreiten und Geräteanschlüsse sind keine Herstellerplanung.</p>
    <p>Zwischen Hochschrankfront und Halbinsel liegen 1,86 m. Halbinsel jetzt 265 × 100 cm, Platte um 5 cm nach Westen auf x = 3,95 m erweitert. Unterbau mit sechs Schrankmodulen: zwei westliche Schränke je 40 cm tief und 50 cm breit, nordseitig 60 cm Vorbereitungsauszug und 105 cm Kochfeldauszug. Südseitig ein 45 cm breiter, 40 cm tiefer Schrank sowie ein 60 cm breiter tiefer Eckschrank mit Zugang von Süden. Nur die 120 × 40 cm große Hockernische bei x = 4,35 bis 5,55 m bleibt frei; die zwei Hocker mit 65 cm Sitzhöhe stehen mittig auf je 60 cm breiten Sitzplätzen. Tisch, Bank und Essstühle unverändert, Tisch und Bank ab z = 7,40 m. Zwischen Insel und Tischkante bleiben 144 cm, ohne Abzug der Barhocker. Einzelne Schranköffnungen geometrisch geprüft, keine Freigabe gleichzeitiger Öffnungen. Wärmeabstände, Lüftung, Beschläge, Anschlüsse und Ergonomie sind herstellerseitig zu prüfen.</p>
    <p>Haustür 110 × 225 cm einschließlich 3-cm-Rahmen, nach innen öffnend und nordseitig angeschlagen; daneben ein 30 cm breites, türhohes Festglas-Seitenteil. Gesamtbreite der Eingangsanlage 140 cm. Normale Innentüren einschließlich neuem Kellerabschluss im EG: 86 × 211 cm einschließlich Zarge; Türblatt 80 × 208 cm. Keine Hersteller- oder Rohbaumaße. Hebeschiebeanlage als weiterer Sonderfall.</p>
    <p>EG-Dusche mit nach innen öffnender, westlich angeschlagener Glastür am nördlichen Zugang, 210 cm hoch. Bisherige feste seitliche Glasscheibe entfernt. Armaturen an der südlichen Rückwand zur Treppe; Kopfbrause auf 223 cm und Wandarm auf 225 cm, oberhalb des Türschwenkbereichs. Duschwanne unverändert. Beschläge, Sicherheitsglas, Abdichtung und Rettungsmöglichkeit bei ausschließlicher Innenöffnung fachlich prüfen.</p>
    <p>OG-Bad mit erweitertem T-Konzept: Dusche jetzt 120 × 141 cm im Südwesten. T-Schirm, Glastür, Waschtisch und Spiegelschrank rücken 24 cm nach Osten; WC im verbreiterten Nordwestbereich zentriert. Einzelwaschtisch weiterhin 135 × 50 cm mit 60-cm-Becken, je 37,5 cm Seitenablage und 10 cm hinter dem Becken. Spiegelschrank 120 × 70 × 16 cm ab 115 cm Höhe. Beide T-Wände 15 cm stark und 242 cm hoch, oben 35 cm offen. Duschöffnung 90 cm mit 210 cm hoher Glastür, nach innen in die Dusche öffnend; mehr als 80 cm freier Durchgang im Modell. WC-Zugang 75 cm. Gang zwischen Waschtisch und unveränderter 180 × 80 cm großer Wanne jetzt 101 cm. Eingang unverändert, Badfläche etwa 10,71 m². Befestigung, Sicherheitsglas, Abdichtung und Anschlüsse fachlich ungeprüft.</p>
    <p>Drei Kellerfenster 90 × 75 cm mit 135 cm Brüstung: östliches Hobbyraumfenster um 240 cm nach Norden auf z = 6,00 bis 6,90 m verschoben. Neues Südfenster bei x = 1,20 bis 2,10 m, mit gleichem Abstand zur Trennwand wie das Nordfenster. Drei Lichtschächte im Grundriss 130 × 50 cm, mittig zum Fenster mit je 20 cm seitlichem Überstand. Gitterstreben einheitlich entlang der jeweiligen Längsachse. Schachtmaße angenähert, nicht gesondert bemaßt; Tiefe, Entwässerung und Herstellerdetails bleiben zu prüfen.</p>
    <p>Fensteröffnungshöhen beider Haushälften im 12,5-cm-Raster; Fensteroberkanten in EG/OG/DG einheitlich 250 cm als durchlaufende Sturzlinie, Haustür unverändert 225 cm. Über den 24 cm hohen Raffstorekästen bleiben 3 cm bis zur Decke. Beide Dachfenster als Klapp-/Schwingfenster, unverändert 94 × 140 cm. Schwingöffnung um die mittlere Achse, untere Flügelhälfte nach innen, modellhaft bis 36 Grad; zusätzliche Klappfunktion vorgesehen, nicht separat animiert. Modellmaße, keine freigegebenen Rohbau- oder Bestellmaße; Beschläge, Fugen, Rahmenanschlüsse, Stürze und Raffstoreeinbau fachlich abzustimmen.</p>
    <p>Fassadenkonzept im Goldenen Schnitt mit vier Formaten: Hochformat 120 × 250 cm, unten über die volle Breite fest bis zur Teilung bei 95 cm (kleinerer Goldener-Schnitt-Anteil der Höhe), darüber ein nach innen öffnender Flügel; Querformat 180 × 112,5 cm (≈ 1:φ) mit Brüstung 137,5 cm, außermittigem Pfosten und 69 cm breitem Lüftungsflügel neben dem Festfeld; Kinderzimmerfenster 180 × 150 cm mit Brüstung 100 cm (Brüstungslinie = Teilungslinie der Hochformate), gleiche Teilung wie das Querformat; Lichtschlitz 60 × 250 cm (≈ φ³) als Festverglasung. Küche, Wohnen und Essen behalten die gemeinsame Sturzlinie 250 cm, die übrigen Räume dürfen darunter bleiben. Ostgiebel: im DG zwei Hochformate symmetrisch zum First bei z = 3,75 bis 4,95 m und 5,55 bis 6,75 m mit 60-cm-Pfeiler; im OG nur das nördliche Hochformat (Kind Nord, Kind Süd hat sein Südfenster); darunter das Küchen-Fensterband 240 × 112,5 cm auf derselben Nordkante bei z = 3,75 bis 6,15 m, Brüstung 137,5 cm über der Arbeitszeile, Lüftungsflügel 92 cm im Süden. Südfassade: Außenlänge 7,00 m im Goldenen Schnitt in 2,70 m Wandscheibe und 4,30 m Glas geteilt; das Glas teilt sich erneut ≈ φ in Hebeschiebeanlage 240 × 250 cm ab x = 2,70 m (Schiebeflügel 120 + Festfeld 120 cm) und feste Eckverglasung 150 × 250 cm ab x = 5,10 m bis zur Glasecke, östliche feste Eckverglasung 120 × 250 cm. Im EG Lichtschlitz bei x = 1,20 bis 1,80 m; im OG Hochformat auf der Schlitzachse und Kinderzimmerfenster auf der östlichen Nordachse bei x = 4,50 bis 6,30 m. Nordfassade: zwei gestapelte Achsen bei x = 0,60 bis 2,40 m und 4,50 bis 6,30 m; im OG Bad-Querformat und Kinderzimmerfenster, im EG darunter Gästebadfenster 60 × 100 cm mit Brüstung 150 cm und flaches Oberlicht 180 × 50 cm mit Brüstung 200 cm über der Garderobe. Gästebadfenster bei x = 0,60 bis 1,20 m sitzt über dem WC (x = 0,57 bis 1,07 m), der Waschtisch mit Spiegelschrank liegt östlich davon. Teilung bei 95 cm ist kein Absturzsicherungsnachweis; Sicherheitsglas, Befestigungen, Rettungswege und Tageslicht fachlich prüfen. Raffstores: EG 7, OG 5, DG 2.</p>
    <p>OG-Flur 120 cm lichte Breite. Beide Kinderzimmer rechnerisch gleich groß mit jeweils 18,60 m²; südliche Trennwand bei z = 7,122 m. Kind Süd misst 6,30 × 2,95 m, Kind Nord im Hauptbereich 2,95 m Breite. Abstellraum 2,70 m². Beide Schreibtische 140 × 60 cm mittig unter den normalen Fenstern bei x = 4,70 bis 6,10 m: Kind Süd an der Südwand, Kind Nord um 90 Grad gedreht an der Nordwand. Stühle, Monitore und Tastaturen zur Tischrichtung ausgerichtet; Monitoroberkante 117 cm. Bett Kind Nord in der Südostecke bei x = 5,55 bis 6,55 m und z = 5,072 bis 7,072 m, Kopfende im Süden, rechts neben dem bodentiefen Ostfenster. Raumwände, übrige Betten, Schränke und Regal unverändert. Spielzimmer entfällt weiterhin. KG, Treppe und Außenmaße unverändert; Tragwerk und Anschlüsse ungeprüft.</p>
    <p>DG-Raumzuordnung: Norden Schlafen / Ankleide mit 15,44 m², Süden Büro / Gäste mit 22,24 m² Grundfläche. Beide Doppelbetten 180 × 200 cm bleiben an ihren Plätzen. L-Schreibtisch samt Stuhl auf die Westseite des Südzimmers versetzt, Blickrichtung Süden; hinter dem Tisch 75 cm bis zur Kommode. Großer Schrank 265 × 43 × 220 cm an die nördliche Treppenwand versetzt, Front nach Norden; kleiner 60-cm-Schrank an der nordwestlichen Abseite. Verbleibender hoher Schrank im Süden an der Wand neben dem Eingang. Nordbett seitlich im Osten 60 cm, im Westen an der Flurwand 65 cm, am Fußende 87 cm frei. Tür und Fenster schwenken frei am Nordbett vorbei; offener Fensterflügel engt den östlichen Bettzugang ein. Stehhöhen unter den Dachschrägen eingeschränkt; Möblierung schematisch, keine Ergonomie- oder Herstellerfreigabe.</p>
    <p>EG-Wohnbereichsverglasung mit gemeinsamer Oberkante 250 cm und bodengleichen Unterkanten; Eckprofil bei x = 6,75/z = 10,35 m. Keine Mauerecke unter dem Sturz; Tragwerk und Eckkopplung ungeprüft. Sitzbank teilweise vor dem Ostfestglas. Keine seitliche Terrassentür in der Ostwand; Gartenzugang über die südliche Hebeschiebeanlage; das Sofa steht teilweise vor dem Schiebeflügel. Über den 75 cm hohen Kinderschreibtischen bleiben 25 cm bis zur Brüstung der Kinderzimmerfenster.</p>
    <p>Warmgraue Außenrahmen, weiße Innenrahmen und gemeinsame Holzfassung um Haustür und Seitenteil an beiden Haushälften; Innen- und Außenfarbe unabhängig je Haus. Raffstores folgen der Außenfarbe. Holzband 20 cm seitlich und 18 cm über der Eingangsanlage. Verglasung weiterhin in der Wandmitte zurückgesetzt. Kein Treppenlichtband in der Haustrennwand. Lüftungsflügel sind kein Rettungsfensternachweis; Rettungswege, Verglasung, Absturzsicherung und Tageslicht sind fachlich zu planen.</p>
    <p>Raffstore-Vorentwurf: 24 cm hohe, 16 cm tiefe Kästen in Aussparungen des äußeren Sturzbereichs mit putzgleicher Front und unterer Revisions-/Austrittsfuge. Führungen 25 mm, profilierte Lamellen 80 mm tief in Rahmenfarbe. An der Glasecke ein durchgehender Südbehang über Schiebe- und Festfeld, separater Ostbehang und gemeinsame Eckführung. Eingang und Keller ohne Raffstores. Absenkung und Lamellenwinkel gemeinsam verstellbar, standardmäßig hochgefahren. Mechanische Visualisierung ohne bewegliche Behang-Kollisionen im Rundgang; keine Motor- oder Windautomatik. Restwand, Tragwerk, Dämmung, Befestigungen, Paketmaße, Revisionszugang, Wärmebrücken und Rettungswege benötigen Hersteller- und Fachplanung.</p>
    <h3>Flächenabgleich</h3>
    <p>Breite Fenster mit außermittigem Pfosten und Lüftungsflügel im kleineren Goldenen-Schnitt-Anteil neben dem Festfeld; bodentiefe 120-cm-Fenster nur waagerecht geteilt. Teilungen und Profile sind Planungsannahmen; keine Dreh-Kipp-Funktion oder Herstellerfreigabe nachgewiesen.</p>
    <p>Die Referenzwerte stammen ausschließlich aus der neuen EG-/OG-Skizze. Für KG und DG liegen keine neuen beschrifteten Pläne vor. Insbesondere die EG-Diele weicht mit den übernommenen Wandstärken und der Garderobennische von der Vorlage ab; Flächen werden nicht künstlich auf deren Beschriftung gesetzt.</p>
    <p>Modell gesamt: {number(totals.floor)} m² lichte Grundfläche; {number(totals.living)} m² überschlägige Wohnfläche.</p>
    <table className="area-comparison"><thead><tr><th>Raum</th><th>Netto Modell / Vorlage</th><th>Wohnen Modell</th></tr></thead><tbody>{floorIds.flatMap(id => makeFloor(id).rooms.map(room => { const actual = roomArea(room, id), reference = referenceAreas[id]?.[room.id]; return <tr key={`${id}-${room.id}`}><th>{id} · {room.name}</th><td>{number(actual.floor)} / {reference === undefined ? '-' : number(reference)}</td><td>{number(actual.living)}</td></tr> }))}</tbody><tfoot>{floorIds.map(id => { const actual = makeFloor(id).rooms.map(room => roomArea(room, id)), reference = referenceAreas[id]; return <tr key={id}><th>Summe {id}</th><td>{number(actual.reduce((sum, room) => sum + room.floor, 0))} / {reference ? number(Object.values(reference).reduce((sum, value) => sum + value, 0)) : '-'}</td><td>{number(actual.reduce((sum, room) => sum + room.living, 0))}</td></tr> })}</tfoot></table>
    <p>Alle Flächen in m². Modellflächen entstehen aus den Raumkonturen, nicht aus den Angebotsbeschriftungen. Wohnfläche: 3 % pauschaler Abzug entsprechend der Tabelle; DG zusätzlich unter 1 m nicht, 1–2 m halb, ab 2 m voll. Türnischen nicht mitgerechnet. Kellerflur einschließlich Treppengrundfläche. Abweichungen insbesondere bei Fluren und Dachschrägen bleiben erkennbar; kein WoFlV-Nachweis.</p>
    <p>Sideboard 180 × 45 × 60 cm, Sofa 250 × 170 cm mit 80 cm normaler Tiefe, lange Seite im Süden und Chaiselongue im Westen. Die Sofagruppe ist 20 cm nach Norden versetzt und hält damit 20 cm Abstand zur inneren Südwandkante. Essstühle zur Tischplatte ausgerichtet; Regal auf 110 cm Breite angepasst. Küche mit Kühlschrank, erhöhtem Backofen, Geschirrspüler, Kochfeld, Espressomaschine, Toaster, SodaStream und Cookit. Bedienflächen und Anschlüsse sind nicht herstellerseitig geprüft.</p>
    <p>Treppe als räumliche Annäherung: 190 × 200 cm, 15 Steigungen, 30 cm gerade Auftritte und nominell 85 cm Laufbreite. 20 cm modellierte Treppenstärke. Radiale Wendelstufen, Geländer und Kopffreiheit benötigen Fachplanung; ein begehbares Kollisionsmodell ersetzt keinen Treppennachweis. Statik, Brand-/Schallschutz, Rettungswege, Abstandsflächen und Vollgeschoss-Einstufung sind nicht nachgewiesen. Grundstück, Nachbarschaft, Garten und Stellplätze bleiben aus dem bisherigen Modell erhalten; die Skizzenlage ist nicht vermessen.</p>
  </>
}