import { basementWindow, construction, elevations, house, interiorWallThickness, rect, stair, standardDoor } from './model'
import type { Floor, FloorId, Furniture, Opening, Rect, Room, Wall } from './model'
import { kitchenFurniture } from './kitchenLayout'

const opening = (id: string, start: number, width = .86, kind: Opening['kind'] = 'door', sill = 0, height = 2.11): Opening => ({ id, start, width, kind, sill, height, ...(kind === 'door' && id !== 'terrace' && height >= 2 ? standardDoor : {}) })
const windowOpening = (id: string, start: number, width: number, sill = .9, height = 1.25): Opening => ({ ...opening(id, start, width, 'window', sill, height), windowLayout: { columns: width >= 1.5 ? 2 : 1, ...(sill === 0 && !id.includes('fixed') ? { lowerFixed: .7 } : {}) } })
const wall = (id: string, axis: Wall['axis'], x: number, z: number, length: number, openings: Opening[] = [], thickness = interiorWallThickness): Wall => ({ id, axis, ...rect(x, z, axis === 'x' ? length : thickness, axis === 'z' ? length : thickness), openings })
const item = (id: string, kind: Furniture['kind'], x: number, z: number, width: number, depth: number, height: number, angle = 0): Furniture => ({ id, kind, x, z, width, depth, height, angle })
const room = (id: string, name: string, parts: Rect[], spawn: [number, number], color = '#e9e7d6', note = 'Aus dem Anbieterplan rekonstruiert; lichte Geometrie, keine Ausführungsplanung.'): Room => ({ id, name, parts, spawn, color, note })

const polygon = (footprint: [number, number][]): Rect => {
  const east = footprint.map(point => point[0]), south = footprint.map(point => point[1])
  return { ...rect(Math.min(...east), Math.min(...south), Math.max(...east) - Math.min(...east), Math.max(...south) - Math.min(...south)), footprint }
}

export const offeredAreas: Record<FloorId, Record<string, [number, number]>> = {
  KG: { bath: [22.13, 0], 'child-north': [5.47, 0], 'child-south': [29.35, 0], hall: [6.56, 0] },
  EG: { wc: [4.52, 4.39], hall: [8.95, 8.68], kitchen: [13.06, 12.67], pantry: [3.28, 3.19], living: [29.35, 28.47] },
  OG: { bath: [10.75, 10.43], hall: [3.42, 3.31], 'child-north': [15.99, 15.51], 'child-south': [15.99, 15.51], bedroom: [13.06, 12.67] },
  DG: { store: [6.14, 2.35], office: [17.91, 15.43], hall: [2.76, 2.67], bedroom: [19.51, 17.73] },
}

export const referenceAreas: Partial<Record<FloorId, Record<string, number>>> = {
  EG: { wc: 4.2, living: 40.2 },
  OG: { bath: 9.2, hall: 3.8, 'child-north': 17, playroom: 7.5, 'child-south': 16.9, store: 2.1 },
}

function shell(id: FloorId): Wall[] {
  const north = id === 'KG' ? [windowOpening('well-plant', .9, basementWindow.width, 1.35, basementWindow.height)] : id === 'EG' ? [windowOpening('wc-window', .3, 1.2, 1.8, .6), windowOpening('hall-window', 2.1, .9, .9, 1.5)] : id === 'OG' ? [windowOpening('bath-window', .3, 2.4, 1.5, .9), windowOpening('child-north-window', 4.2, 1.5, .9, 1.5)] : []
  const east: Opening[] = id === 'KG' ? [windowOpening('well-hobby', house.depth - basementWindow.southGap - basementWindow.width, basementWindow.width, 1.35, basementWindow.height)] : id === 'EG' ? [windowOpening('entrance-fixed', .3, .3, 0, 2.52), { ...opening('entrance', .6), width: 1.1, height: 2.52, swing: 'reverse' }, windowOpening('kitchen-east-window', 3.3, 1.5, 1.2, 1.2), windowOpening('living-east', 6.3, 1.5, 1.2, 1.2), { ...windowOpening('living-corner-fixed', 9.3, 1.2, 0, 2.52), cornerGlazing: true }] : id === 'OG' ? [windowOpening('east-north', 3.3, 1.5, .9, 1.5), windowOpening('play-window', 6.3, 1.5, .9, 1.5)] : [{ ...windowOpening('gable-office', 3.3, 1.5, 0, 2.1), windowLayout: { columns: 2, lowerFixed: .6 } }, { ...windowOpening('gable-parents', 6.3, 1.5, 0, 2.1), windowLayout: { columns: 2, lowerFixed: .6 } }]
  const southWallLength = house.east - house.west
  const terraceWidth = 2.5, terraceLeaf = terraceWidth / 2
  const terraceStart = southWallLength - terraceWidth - construction.exteriorWall
  const south: Opening[] = id === 'EG' ? [windowOpening('garden-west', .6, 1.8, 0, 2.4), opening('terrace', terraceStart, terraceLeaf, 'door', 0, 2.52), { ...windowOpening('garden-fixed', terraceStart + terraceLeaf, terraceLeaf + construction.exteriorWall, 0, 2.52), cornerGlazing: true, windowLayout: { columns: 1 } }] : id === 'OG' ? [windowOpening('south-west', .6, 1.8, .9, 1.5), windowOpening('south-east', southWallLength - construction.exteriorWall - 1.8, 1.8, .9, 1.5)] : []
  if (id === 'EG') for (const glazed of [...east, ...south].filter(opening => opening.kind === 'window' && opening.sill === 0)) glazed.windowLayout = { columns: glazed.windowLayout!.columns }
  return [wall('west', 'z', 0, 0, house.depth, [], house.west), wall('east', 'z', house.east, 0, house.depth, east, construction.exteriorWall), wall('north', 'x', house.west, 0, house.east - house.west, north, construction.exteriorWall), wall('south', 'x', house.west, house.south, house.east - house.west, south, construction.exteriorWall)]
}

export function buildProviderFloor(id: FloorId, side: 'east' | 'west'): Floor {
  const floor: Floor = { id, name: { KG: 'Kellergeschoss', EG: 'Erdgeschoss', OG: 'Obergeschoss', DG: 'Dachgeschoss' }[id], elevation: elevations[id], height: id === 'KG' ? construction.basementClearHeight : construction.clearHeight, rooms: [], walls: shell(id), furniture: [] }
  if (side === 'west') return floor
  const west = house.west, east = house.east, north = house.north, south = house.south, partition = interiorWallThickness
  const bearing = .2
  const stairEast = stair.x + stair.width, hallWest = stairEast + partition, upperNorth = stair.z - bearing, lowerSouth = stair.end + bearing
  if (id !== 'KG') floor.walls.push(wall('stair-north', 'x', west, upperNorth, stair.width, [], bearing), wall('stair-south', 'x', west, stair.end, stair.width, [], bearing))
  if (id === 'EG') {
    const bathEast = 2.15, nicheWest = 1.4, nicheNorth = 1.85, screenWest = 3.3, screenEast = 3.45
    const diagonalAtWall = screenWest + (2.65 - screenWest) * (stair.end - 4.3) / (lowerSouth - 4.3)
    floor.walls.push(wall('wc-east', 'z', bathEast, north, nicheNorth - north, [{ ...opening('wc', .6, .85), swing: 'reverse' }]), wall('wc-niche-north', 'x', nicheWest - partition, nicheNorth, bathEast - nicheWest + partition), wall('wc-niche-return', 'z', nicheWest - partition, nicheNorth + partition, upperNorth - nicheNorth - partition), wall('kitchen-west', 'z', screenWest, 1.7, 2.6, [], .15), wall('kitchen-north', 'x', screenEast, 2.35, east - screenEast, [], .15), { id: 'living-diagonal', axis: 'z', ...polygon([[screenWest, 4.3], [screenEast, 4.3], [2.8, lowerSouth], [2.65, lowerSouth]]), openings: [opening('living-passage', 0, lowerSouth - 4.3, 'passage', 0, floor.height)] }, { id: 'stair-south-extension', axis: 'x', ...polygon([[stairEast, stair.end], [diagonalAtWall, stair.end], [2.65, lowerSouth], [stairEast, lowerSouth]]), openings: [] }, { ...wall('wc-installation-north', 'x', west, north, bathEast - west, [], .08), height: 1.2 })
    floor.rooms = [room('wc', 'Gästebad', [rect(west, north + .08, bathEast - west, nicheNorth - north - .08), rect(west, nicheNorth, nicheWest - partition - west, upperNorth - nicheNorth)], [1.1, 1.4], '#d8e8ea', 'Nordwestliches Gästebad mit Dusche, WC und Waschtisch. Schmale Vorwand im Norden und Unterputzarmaturen als Planungsannahme; Anschlüsse ungeprüft.'), room('entry', 'Diele', [rect(screenWest, north, east - screenWest, 1.7 - north), rect(screenEast, 1.7, east - screenEast, .65)], [5.65, 1.15], '#e5e2d7'), room('hall', 'Flur', [rect(bathEast + partition, north, screenWest - bathEast - partition, 1.7 - north), rect(bathEast + partition, 1.7, screenWest - bathEast - partition, upperNorth - 1.7), rect(nicheWest, nicheNorth + partition, bathEast - nicheWest + partition, upperNorth - nicheNorth - partition), rect(hallWest, upperNorth, screenWest - hallWest, 4.3 - upperNorth), polygon([[hallWest, 4.3], [screenWest, 4.3], [diagonalAtWall, stair.end], [stairEast, stair.end], [stairEast, upperNorth + 1.11], [hallWest, upperNorth + 1.11]])], [2.75, 2.75], '#edece4'), room('living', 'Wohnen / Kochen / Essen', [rect(screenEast, 2.5, east - screenEast, 1.8), polygon([[screenEast, 4.3], [east, 4.3], [east, lowerSouth], [2.8, lowerSouth]]), rect(west, lowerSouth, east - west, south - lowerSouth)], [3.6, 7.1], '#eee8cf', 'Offene Küche östlich der Treppe mit fünf Hochschränken, Arbeitszeilen und Halbinsel. Essplatz im Südosten, Wohnecke im Südwesten; schräge Dielenwand nach Vorlage.')]
    floor.walls.push(wall('basement-entry', 'z', stairEast, upperNorth, 1.11, [opening('basement-stair', .19)]))
    floor.rooms.find(room => room.id === 'entry')!.tileParts = [rect(screenWest, north, east - screenWest, 1.7 - north), rect(screenEast, 1.7, east - screenEast, .65)]
    floor.furniture = [...kitchenFurniture(floor.height), { ...item('guest-shower', 'shower', .33, upperNorth - 1.12, .9, 1.08, .04), concealedFittings: true }, { ...item('guest-wc', 'wc', .57, .39, .5, .65, .43), concealedFittings: true }, { ...item('guest-sink', 'sink', 1.42, .39, .55, .45, .85), concealedFittings: true },
      { ...item('cleaning-storage', 'cabinet', nicheWest, nicheNorth + partition, bathEast + partition - nicheWest, upperNorth - nicheNorth - partition, floor.height), front: 'east' },
      { ...item('entry-coats', 'coat-rack', screenEast, north, 2.1, .1, .18), bottom: 1.5 },
      { ...item('wardrobe', 'cabinet', screenEast, 1.75, 2.1, .6, floor.height), front: 'north' },
      item('sideboard', 'cabinet', .55, lowerSouth + .2, 1.8, .45, .6), item('tv', 'tv', .77, lowerSouth + .22, 1.3, .08, 1.45), item('bookshelf', 'bookcase', .35, 6.5, .4, 1.1, 2.12), item('dining', 'table', 5.2, 7.75, .9, 1.8, .75), item('dining-bench', 'bench', 6.15, 7.75, .4, 1.8, .85), item('sofa', 'sofa', .4, 9.2, 2.5, .8, .8, Math.PI), item('sofa-chaise', 'chaise', .4, 8.3, .8, .9, .48), item('coffee', 'table', 1.5, 8.4, .9, .8, .35), item('lounge-chair', 'chair', 2.2, 7.45, .65, .7, .85), ...[7.9, 8.5, 9.1].map((south, index) => item(`dining-chair-${index}`, 'chair', 4.5, south, .43, .43, .8, -Math.PI / 2)), ...[4.55, 5.25].map((east, index) => ({ ...item(`kitchen-stool-${index}`, 'chair', east, 6.4, .43, .4, .68), seatHeight: .65 }))]
  } else if (id === 'KG') {
    const divider = 3.625
    floor.walls.push(wall('bath-south', 'x', west, upperNorth, east - west, [opening('bath', 2.3)], bearing), wall('east-divider', 'z', divider, stair.z, stair.depth, [opening('child-north', .35)]), wall('store-north', 'x', west, stair.end, east - west, [opening('child-south', 2.3)], bearing))
    floor.rooms = [room('bath', 'Technik / Lager', [rect(west, north, east - west, upperNorth - north)], [3.7, 2.1], '#e4e7e8'), room('child-north', 'Keller', [rect(divider + partition, stair.z, east - divider - partition, stair.depth)], [4.9, 4.7], '#e4e7e8'), room('child-south', 'Keller / Hobby', [rect(west, lowerSouth, east - west, south - lowerSouth)], [3.5, 8.1], '#e4e7e8'), room('hall', 'Kellerflur', [rect(west, stair.z, divider - west, stair.depth)], [2.85, 4.65], '#eeeee8', 'Einschließlich Treppengrundfläche; keine Wohnfläche.')]
    floor.furniture = [item('heat-pump', 'machine', .45, .45, .75, .75, 1.8), item('tank', 'machine', 1.4, .45, .7, .7, 1.7), item('washer', 'machine', 4.85, .45, .62, .62, .88), item('dryer', 'machine', 5.55, .45, .62, .62, .88), item('utility-shelf', 'bookcase', .4, upperNorth - 1.4, .4, 1.3, 2), item('cellar-shelf', 'bookcase', east - .45, stair.z + .1, .35, 1.8, 2), item('hobby-table', 'table', 4.9, 7.7, 1.3, .7, .75), item('hobby-sofa', 'sofa', .45, south - .9, 2, .8, .8)]
  } else if (id === 'OG') {
    const divider = 3.45, childWest = divider + partition, split = 5.7, playSouth = 8.225, hallEnd = 6.875, storeSouth = 6.8
    // T-Bad: Waschtisch-Vorwand mittig, dahinter westlich Dusche (Nord) und WC (Süd) an einer Installationswand; Durchgänge je 85 cm
    const wetEast = 1.3, screenThickness = .15, screenEast = wetEast + screenThickness, screenNorth = 1.15, screenSouth = 2.45, serviceNorth = 1.6, serviceDepth = .15, vanityDepth = .5, sinkWidth = .6
    floor.walls.push(wall('bath-south', 'x', stairEast, upperNorth, divider - stairEast, [{ ...opening('bath', .225, .85), hinge: 'end' }], bearing), wall('east-divider', 'z', divider, north, playSouth + partition - north, [{ ...opening('child-north', 3.7, .85), hinge: 'end' }, opening('playroom', 5.6, .85)]), wall('children-divider', 'x', childWest, split, east - childWest), wall('playroom-south', 'x', childWest, playSouth, east - childWest), wall('bedroom-north', 'x', stairEast, hallEnd, divider - stairEast, [{ ...opening('child-south', .225, .85), hinge: 'end', swing: 'reverse' }]), wall('store-east', 'z', stairEast, lowerSouth, storeSouth - lowerSouth, [{ ...opening('store', .1, .85), swing: 'reverse' }]), wall('store-south', 'x', west, storeSouth, stair.width, [], bearing), wall('bath-installation', 'x', west, serviceNorth, wetEast - west, [], serviceDepth), wall('bath-screen', 'z', wetEast, screenNorth, screenSouth - screenNorth, [], screenThickness))
    floor.rooms = [room('bath', 'Bad', [rect(west, north, wetEast - west, serviceNorth - north), rect(west, serviceNorth + serviceDepth, wetEast - west, upperNorth - serviceNorth - serviceDepth), rect(wetEast, north, screenThickness, screenNorth - north), rect(wetEast, screenSouth, screenThickness, upperNorth - screenSouth), rect(screenEast, north, divider - screenEast, upperNorth - north)], [2.45, 2.8], '#d8e8ea', 'T-Bad nach Vorlage: Waschtisch-Vorwand mittig mit einem Becken und Ablage beidseitig, dahinter bodengleiche Dusche 96 x 126 cm im Nordwesten und WC im Südwesten an einer 15-cm-Installationswand; Durchgänge je 85 cm. Wanne 180 x 80 cm an der Ostwand; 240 x 90 cm Nordlichtband. Anschlüsse ungeprüft.'), room('child-north', 'Kind Nord', [rect(childWest, north, east - childWest, split - north)], [5.05, 3.3], '#e9ecd9'), room('playroom', 'Spielzimmer', [rect(childWest, split + partition, east - childWest, playSouth - split - partition)], [5.1, 7.1], '#eee8cf'), room('child-south', 'Kind Süd', [rect(west, hallEnd + partition, divider - west, playSouth - hallEnd), rect(west, playSouth + partition, east - west, south - playSouth - partition)], [2.7, 8.1], '#e9ecd9'), room('hall', 'Flur', [rect(hallWest, stair.z, divider - hallWest, hallEnd - stair.z)], [(hallWest + divider) / 2, 5.2], '#eeeee8'), room('store', 'Abstellraum', [rect(west, lowerSouth, stairEast - west, storeSouth - lowerSouth)], [1.25, 6.45])]
    floor.furniture = [item('bath-tub', 'bath', divider - .8, .35, .8, 1.8, .6), { ...item('bath-shower', 'shower', west + .02, north + .02, wetEast - west - .04, serviceNorth - north - .04, .04, Math.PI), concealedFittings: true }, { ...item('bath-wc', 'wc', (west + wetEast) / 2 - .25, serviceNorth + serviceDepth + .01, .5, .65, .43), concealedFittings: true }, { ...item('bath-vanity', 'cabinet', screenEast, screenNorth, vanityDepth, screenSouth - screenNorth, .67), front: 'east' }, { ...item('bath-sink', 'sink', screenEast, (screenNorth + screenSouth - sinkWidth) / 2, vanityDepth, sinkWidth, .85, -Math.PI / 2), concealedFittings: true }, item('bed-north', 'bed', 3.68, .45, 1, 2, .52), item('desk-north', 'desk', 5.95, 2.55, .6, 1.4, .75), item('desk-chair-north', 'chair', 5.32, 3.02, .48, .48, .82), item('wardrobe-north', 'cabinet', 4.55, 5.05, 2, .6, 2.3), item('bed-south', 'bed', .45, 7.3, 1, 2, .52), item('desk-south', 'desk', 2.15, 9.55, 1.4, .6, .75), item('desk-chair-south', 'chair', 2.6, 8.9, .48, .48, .82), { ...item('wardrobe-south', 'cabinet', 4.35, playSouth + partition, 2, .6, 2.3), front: 'south' }, item('play-shelf', 'bookcase', 4.55, 5.88, 1.8, .35, 1.1), item('play-table', 'table', 5.2, 7.4, 1.1, .65, .55), item('play-chair', 'chair', 4.65, 7.5, .4, .4, .65), item('store-shelf', 'bookcase', .35, 5.75, .35, 1, 2)]
  } else {
    const usableNorth = 1.72, usableSouth = south, parentsSouth = south - 1.2, divider = 3.425, officeEnd = stair.end - .4, hallEnd = stair.end, storeEast = 2.95, storeNorth = usableSouth - 6.14 / (storeEast - west)
    floor.walls.push(wall('knee-north', 'x', west, usableNorth - partition, east - west), wall('knee-south', 'x', storeEast + partition, parentsSouth, east - storeEast - partition), wall('hall-north', 'x', stairEast, upperNorth, divider + partition - stairEast, [], bearing), wall('office-west', 'z', divider, stair.z, officeEnd - stair.z, [{ ...opening('attic-office', .08, .85), hinge: 'end' }]), wall('office-entry', 'x', divider, officeEnd, east - divider), wall('parents-entry-south', 'x', stairEast, hallEnd, divider + partition - stairEast, [opening('attic-parents-south', partition, .85)], bearing), wall('store-north', 'x', west, storeNorth - partition, storeEast - west), wall('store-east', 'z', storeEast, storeNorth - partition, usableSouth - storeNorth + partition, [{ ...opening('store', .025, .73, 'door', 0, 1.6), swing: 'reverse' }]), wall('bedroom-west', 'z', divider, officeEnd + partition, hallEnd - officeEnd - partition))
    floor.rooms = [room('office', 'Büro', [rect(west, usableNorth, east - west, upperNorth - usableNorth), rect(divider + partition, upperNorth, east - divider - partition, officeEnd - upperNorth)], [4.9, 3.7], '#e4e8e2'), room('hall', 'Flur', [rect(hallWest, stair.z, divider - hallWest, hallEnd - stair.z)], [2.85, 4.8], '#eeeee8'), room('store', 'Abstellraum', [rect(west, storeNorth, storeEast - west, usableSouth - storeNorth)], [1.5, 8.65], '#e8e7df'), room('bedroom', 'Schlafen / Ankleide', [rect(divider + partition, officeEnd + partition, east - divider - partition, lowerSouth - officeEnd - partition), rect(west, lowerSouth, east - west, storeNorth - partition - lowerSouth), rect(storeEast + partition, storeNorth - partition, east - storeEast - partition, parentsSouth - storeNorth + partition)], [3.3, 6.8])]
    floor.furniture = [item('office-desk', 'desk', .35, 1.79, 2, .7, .75), item('office-desk-return', 'table', .35, 2.49, .7, .7, .75), item('office-chair', 'chair', 1.35, 2.7, .48, .48, .85), item('office-storage', 'cabinet', 3.1, 1.78, 2.3, .4, 1.0), item('office-south-storage', 'cabinet', 4.4, officeEnd - .48, 1.2, .45, 1.1), item('office-plant-west', 'plant', 2.5, 1.83, .4, .4, 1.0), item('office-plant-east', 'plant', 6.05, 1.83, .4, .4, 1.0), item('parents-bed', 'bed', 4.4, parentsSouth - 2.05, 1.8, 2, .52, Math.PI), item('parents-north-storage', 'cabinet', 3.6, officeEnd + partition + .03, 2.65, .43, 2.2), item('parents-cabinet', 'cabinet', .4, lowerSouth + .04, 1.7, .6, 2.25), item('dressing-low', 'cabinet', .4, storeNorth - partition - .45, 2.45, .45, 1.4), item('store-shelf', 'bookcase', .4, south - .75, 2.4, .35, .55), item('parents-low', 'cabinet', 3.25, parentsSouth - .5, .6, .45, .7), item('parents-low-east', 'cabinet', east - .35, parentsSouth - .5, .3, .45, .7)]
  }
  for (const chair of floor.furniture.filter(item => ['desk-chair-north', 'play-chair', 'office-chair'].includes(item.id))) chair.angle = chair.id === 'office-chair' ? Math.PI : -Math.PI / 2
  return floor
}