import { basementWindow, construction, elevations, house, interiorWallThickness, rect, stair } from './model'
import type { Floor, FloorId, Furniture, Opening, Rect, Room, Wall } from './model'
import { kitchenFurniture } from './kitchenLayout'

const opening = (id: string, start: number, width = .9, kind: Opening['kind'] = 'door', sill = 0, height = 2): Opening => ({ id, start, width, kind, sill, height })
const windowOpening = (id: string, start: number, width: number, sill = .9, height = 1.25): Opening => ({ ...opening(id, start, width, 'window', sill, height), windowLayout: { columns: width >= 1.5 ? 2 : 1, ...(sill === 0 && !id.includes('fixed') ? { lowerFixed: .7 } : {}) } })
const wall = (id: string, axis: Wall['axis'], x: number, z: number, length: number, openings: Opening[] = [], thickness = interiorWallThickness): Wall => ({ id, axis, ...rect(x, z, axis === 'x' ? length : thickness, axis === 'z' ? length : thickness), openings })
const item = (id: string, kind: Furniture['kind'], x: number, z: number, width: number, depth: number, height: number, angle = 0): Furniture => ({ id, kind, x, z, width, depth, height, angle })
const room = (id: string, name: string, parts: Rect[], spawn: [number, number], color = '#e9e7d6', note = 'Aus dem Anbieterplan rekonstruiert; lichte Geometrie, keine Ausführungsplanung.'): Room => ({ id, name, parts, spawn, color, note })

const getGroundFloorNorthShift = () => 3.28 / (house.east - 3.825 - interiorWallThickness) + interiorWallThickness

export const offeredAreas: Record<FloorId, Record<string, [number, number]>> = {
  KG: { bath: [22.13, 0], 'child-north': [5.47, 0], 'child-south': [29.35, 0], hall: [6.56, 0] },
  EG: { wc: [4.52, 4.39], hall: [8.95, 8.68], kitchen: [13.06, 12.67], pantry: [3.28, 3.19], living: [29.35, 28.47] },
  OG: { bath: [10.75, 10.43], hall: [3.42, 3.31], 'child-north': [15.99, 15.51], 'child-south': [15.99, 15.51], bedroom: [13.06, 12.67] },
  DG: { store: [6.14, 2.35], office: [17.91, 15.43], hall: [2.76, 2.67], bedroom: [19.51, 17.73] },
}

function shell(id: FloorId): Wall[] {
  const groundFloorNorthShift = getGroundFloorNorthShift()
  const north = id === 'KG' ? [windowOpening('well-plant', .9, basementWindow.width, 1.35, basementWindow.height)] : id === 'EG' ? [windowOpening('kitchen-window', .6, 1.8)] : id === 'OG' ? [windowOpening('bath-window', .6, 1.8), windowOpening('child-north-window', 4.2, 1.2, 0, 2.52)] : []
  const east: Opening[] = id === 'KG' ? [windowOpening('well-hobby', house.depth - basementWindow.southGap - basementWindow.width, basementWindow.width, 1.35, basementWindow.height)] : id === 'EG' ? [windowOpening('wc-window', 1.9 - groundFloorNorthShift, .8, 1.3, 1.05), { ...opening('entrance', 4.2 - groundFloorNorthShift, 1.13, 'door', 0, 2.52), hinge: 'end', swing: 'reverse' }, windowOpening('living-east', 8.7, 1.8)] : id === 'OG' ? [windowOpening('east-north', .9, 1.8), windowOpening('east-south', 8.7, 1.8)] : [windowOpening('gable-office', 3.3, 1.8, 0, 2.27), windowOpening('gable-parents', 6.3, 1.8, 0, 2.27)]
  const south: Opening[] = id === 'EG' ? [opening('garden-door', .6, .9, 'door', 0, 2.52), { ...opening('garden-door-secondary', 1.5, .9, 'door', 0, 2.52), hinge: 'end' }, windowOpening('garden-fixed', 3.6, 1.8, 0, 2.52)] : id === 'OG' ? [windowOpening('south-west', .6, 1.2, 0, 2.52), windowOpening('south-east', 4.2, 1.2, 0, 2.52)] : []
  return [wall('west', 'z', 0, 0, house.depth, [], house.west), wall('east', 'z', house.east, 0, house.depth, east, construction.exteriorWall), wall('north', 'x', house.west, 0, house.east - house.west, north, construction.exteriorWall), wall('south', 'x', house.west, house.south, house.east - house.west, south, construction.exteriorWall)]
}

export function buildProviderFloor(id: FloorId, side: 'east' | 'west'): Floor {
  const floor: Floor = { id, name: { KG: 'Kellergeschoss', EG: 'Erdgeschoss', OG: 'Obergeschoss', DG: 'Dachgeschoss' }[id], elevation: elevations[id], height: id === 'KG' ? construction.basementClearHeight : construction.clearHeight, rooms: [], walls: shell(id), furniture: [] }
  if (side === 'west') return floor
  const west = house.west, east = house.east, north = house.north, south = house.south, partition = interiorWallThickness
  const bearing = .2
  const stairEast = stair.x + stair.width, hallWest = stairEast + partition, upperNorth = stair.z - bearing, lowerSouth = stair.end + bearing
  if (id !== 'KG') floor.walls.push(wall('stair-north', 'x', west, upperNorth, stair.width, [], bearing), wall('stair-south', 'x', west, stair.end, stair.width, [], bearing))
  if (id === 'EG') {
    const groundFloorNorthShift = getGroundFloorNorthShift()
    const kitchenEast = 3.825, wetWest = kitchenEast + partition, showerNorth = north
    const bathSouth = upperNorth - groundFloorNorthShift, hallNorth = bathSouth + bearing
    const nicheWest = wetWest + .9 + partition, showerEnd = bathSouth - .48
    const livingNorth = stair.end - groundFloorNorthShift, screenWest = east - 1.55
    floor.walls.push(wall('kitchen-east', 'z', kitchenEast, north, upperNorth - north), wall('wc-south', 'x', wetWest, bathSouth, .9, [opening('wc', .025, .85)], bearing), wall('wc-niche-return', 'z', nicheWest - partition, showerEnd, hallNorth - showerEnd), wall('wc-niche-north', 'x', nicheWest, showerEnd, east - nicheWest), wall('living-north', 'x', screenWest, livingNorth, east - screenWest, [], bearing))
    const serviceEast = east - .2, showerServiceWidth = .96, showerServiceDepth = .1
    floor.walls.push({ ...wall('wc-installation-east', 'z', serviceEast, showerNorth, showerEnd - showerNorth, [], .2), height: 1.2 }, { ...wall('wc-installation-shower', 'x', wetWest, showerNorth, showerServiceWidth, [], showerServiceDepth), height: 2.2 })
    floor.rooms = [room('kitchen', 'Küche', [rect(west, north, kitchenEast - west, upperNorth - north)], [2.1, 2.4]), room('wc', 'Dusche', [rect(wetWest + showerServiceWidth, showerNorth, serviceEast - wetWest - showerServiceWidth, showerServiceDepth), rect(wetWest, showerNorth + showerServiceDepth, serviceEast - wetWest, showerEnd - showerNorth - showerServiceDepth), rect(wetWest, showerEnd, .9, bathSouth - showerEnd)], [5.1, 2.95 - groundFloorNorthShift], '#d8e8ea', 'In die ehemalige Speisekammer nach Norden verschoben. Dusche im Nordwesten, WC und Waschtisch an der östlichen Vorwand, Unterputzarmaturen. Vorwandflächen abgezogen; Aufbauten und Leitungsführung sind Planungsannahmen.'), room('hall', 'Diele', [rect(wetWest, hallNorth, east - wetWest, upperNorth - hallNorth), rect(stairEast, upperNorth, east - stairEast, livingNorth - upperNorth), rect(nicheWest, showerEnd + partition, east - nicheWest, hallNorth - showerEnd - partition)], [4.55, 3.35], '#edece4'), room('living', 'Wohnen / Essen', [rect(stairEast, livingNorth, screenWest - stairEast, bearing), rect(stairEast, livingNorth + bearing, east - stairEast, lowerSouth - livingNorth - bearing), rect(west, lowerSouth, east - west, south - lowerSouth)], [3.25, 8.55], '#eee8cf', 'Offener Anschluss an Diele und Küche, kurze Garderobenwand. Bestandssofa 250 × 170 cm, Sideboard 180 × 45 × 60 cm und Bücherregal 212 × 40 × 212 cm. Tisch 180 × 90 cm an der Westwand; sechs Stühle.')]
    floor.furniture = [...kitchenFurniture(floor.height), { ...item('guest-shower', 'shower', 3.98, showerNorth + showerServiceDepth + .01, .9, .9, .04), concealedFittings: true }, { ...item('guest-wc', 'wc', serviceEast - .65, showerNorth + .1, .65, .5, .43, Math.PI / 2), concealedFittings: true }, { ...item('guest-sink', 'sink', serviceEast - .5, showerEnd - .68, .5, .65, .85, Math.PI / 2), concealedFittings: true }, item('hall-niche-storage', 'cabinet', nicheWest + .025, showerEnd + partition + .02, east - nicheWest - .05, .43, 2.3), item('wardrobe', 'cabinet', screenWest + .05, livingNorth - .52, 1.45, .5, 2.35, Math.PI), item('bookshelf', 'bookcase', .35, lowerSouth + .02, 2.12, .4, 2.12), item('sideboard', 'cabinet', 4.43, lowerSouth + .03, 1.8, .45, .6), item('tv', 'tv', 4.65, lowerSouth + .09, 1.3, .08, 1.45), item('dining', 'table', .35, 7.85, 1.8, .9, .75), item('sofa', 'sofa', 5.45, 8.35, .8, 2.5, .8, Math.PI / 2), item('sofa-chaise', 'chaise', 4.55, 10.05, .9, .8, .48), item('coffee', 'table', 4.05, 9.25, .9, .5, .35), item('plant', 'plant', 5.75, 7.1, .4, .4, 1.2), ...[.48, 1.06, 1.64].flatMap((x, index) => [item(`dining-chair-n-${index}`, 'chair', x, 7.25, .43, .43, .8), item(`dining-chair-s-${index}`, 'chair', x, 8.92, .43, .43, .8, Math.PI)])]
  } else if (id === 'KG') {
    const divider = 3.625
    floor.walls.push(wall('bath-south', 'x', west, upperNorth, east - west, [opening('bath', 2.3)], bearing), wall('east-divider', 'z', divider, stair.z, stair.depth, [opening('child-north', .35)]), wall('store-north', 'x', west, stair.end, east - west, [opening('child-south', 2.3)], bearing))
    floor.rooms = [room('bath', 'Technik / Lager', [rect(west, north, east - west, upperNorth - north)], [3.7, 2.4], '#e4e7e8'), room('child-north', 'Keller', [rect(divider + partition, stair.z, east - divider - partition, stair.depth)], [4.9, 5.2], '#e4e7e8'), room('child-south', 'Keller / Hobby', [rect(west, lowerSouth, east - west, south - lowerSouth)], [3.5, 8.1], '#e4e7e8'), room('hall', 'Kellerflur', [rect(west, stair.z, divider - west, stair.depth)], [2.8, 5.3], '#eeeee8', 'Wie in der Angebotsaufstellung einschließlich Treppengrundfläche; keine Wohnfläche.')]
    floor.furniture = [item('heat-pump', 'machine', .45, .45, .75, .75, 1.8), item('tank', 'machine', 1.4, .45, .7, .7, 1.7), item('washer', 'machine', 4.85, .45, .62, .62, .88), item('dryer', 'machine', 5.55, .45, .62, .62, .88), item('utility-shelf', 'bookcase', .4, 2.2, .4, 1.3, 2), item('cellar-shelf', 'bookcase', 5.85, 4.2, .35, 1.8, 2), item('hobby-table', 'table', 4.9, 8.2, 1.3, .7, .75), item('hobby-sofa', 'sofa', .45, 9.9, 2, .8, .8)]
  } else if (id === 'OG') {
    const divider = hallWest + 1, childWest = divider + partition, split = (north + south - partition) / 2, hallEnd = 7.35
    floor.walls.push(wall('bath-south', 'x', stairEast, upperNorth, divider - stairEast, [{ ...opening('bath', .075, .85), hinge: 'end' }], bearing), wall('east-divider', 'z', divider, north, south - north, [{ ...opening('child-north', 3.7, .85), hinge: 'end' }, opening('child-south', 6.15, .85)]), wall('children-divider', 'x', childWest, split, east - childWest), wall('bedroom-north', 'x', stairEast, hallEnd, divider - stairEast, [{ ...opening('bedroom', .075, .85), hinge: 'end', swing: 'reverse' }]), wall('bedroom-hall', 'z', stairEast, stair.end, hallEnd - stair.end))
    floor.walls.push({ ...wall('bath-installation-east', 'z', divider - .2, north, 2.4, [], .2), height: 1.2 }, { ...wall('bath-installation-west', 'z', west, north, 2.4, [], .12), height: 1.05 })
    floor.rooms = [room('bath', 'Bad', [rect(west + .12, north, divider - .2 - west - .12, 2.4), rect(west, north + 2.4, divider - west, upperNorth - north - 2.4)], [1.8, 2.55], '#d8e8ea'), room('child-north', 'Kind Nord', [rect(childWest, north, east - childWest, split - north)], [4.9, 3.7], '#e9ecd9'), room('child-south', 'Kind Süd', [rect(childWest, split + partition, east - childWest, south - split - partition)], [4.9, 8.0], '#e9ecd9'), room('hall', 'Flur', [rect(hallWest, stair.z, divider - hallWest, hallEnd - stair.z)], [(hallWest + divider) / 2, 5.65], '#eeeee8'), room('bedroom', 'Zimmer', [rect(west, lowerSouth, stairEast - west, hallEnd + partition - lowerSouth), rect(west, hallEnd + partition, divider - west, south - hallEnd - partition)], [1.65, 8.5])]
    floor.furniture = [item('bath-tub', 'bath', .44, .45, .8, 1.8, .6), item('bath-shower', 'shower', .38, upperNorth - 1.02, .95, .95, .04), item('bath-wc', 'wc', divider - .85, .55, .65, .5, .43, Math.PI / 2), item('bath-sink', 'sink', divider - .72, 1.55, .52, .85, .85, Math.PI / 2), item('bed-north', 'bed', 3.45, .45, .9, 2, .52), item('desk-north', 'desk', 5.6, 2.65, .6, 1.4, .75), item('desk-chair-north', 'chair', 4.88, 3.12, .48, .48, .82), item('wardrobe-north', 'cabinet', 3.45, 4.98, 2.7, .6, 2.3), item('bed-south', 'bed', 3.45, 8.9, .9, 2, .52), item('desk-south', 'desk', 5.6, 7.5, .6, 1.4, .75), item('desk-chair-south', 'chair', 4.88, 7.95, .48, .48, .82), item('wardrobe-south', 'cabinet', 3.45, 5.8, 2.7, .6, 2.3), item('room-bed', 'bed', .45, 8.8, .9, 2, .52), item('room-desk', 'desk', 2.5, 8.45, .6, 1.4, .75), item('room-chair', 'chair', 1.8, 8.9, .48, .48, .82), item('room-wardrobe', 'cabinet', .4, lowerSouth + .04, 1.7, .6, 2.3)]
  } else {
    const usableNorth = 1.72, usableSouth = south, parentsSouth = 9.9, divider = 3.425, officeEnd = 5.585, hallEnd = stair.end, storeEast = 2.95, storeNorth = usableSouth - 6.14 / (storeEast - west)
    floor.walls.push(wall('knee-north', 'x', west, usableNorth - partition, east - west), wall('knee-south', 'x', storeEast + partition, parentsSouth, east - storeEast - partition), wall('hall-north', 'x', stairEast, upperNorth, divider + partition - stairEast, [], bearing), wall('office-west', 'z', divider, stair.z, officeEnd - stair.z, [{ ...opening('attic-office', .08, .85), hinge: 'end' }]), wall('office-entry', 'x', divider, officeEnd, east - divider), wall('parents-entry-south', 'x', stairEast, hallEnd, divider + partition - stairEast, [opening('attic-parents-south', partition, .85)], bearing), wall('store-north', 'x', west, storeNorth - partition, storeEast - west), wall('store-east', 'z', storeEast, storeNorth - partition, usableSouth - storeNorth + partition, [{ ...opening('store', .025, .73, 'door', 0, 1.6), swing: 'reverse' }]), wall('bedroom-west', 'z', divider, officeEnd + partition, hallEnd - officeEnd - partition))
    floor.rooms = [room('office', 'Büro', [rect(west, usableNorth, east - west, upperNorth - usableNorth), rect(divider + partition, upperNorth, east - divider - partition, officeEnd - upperNorth)], [4.8, 3.8], '#e4e8e2'), room('hall', 'Flur', [rect(hallWest, stair.z, divider - hallWest, hallEnd - stair.z)], [2.85, 5.55], '#eeeee8'), room('store', 'Abstellraum', [rect(west, storeNorth, storeEast - west, usableSouth - storeNorth)], [2.3, 8.97], '#e8e7df'), room('bedroom', 'Schlafen / Ankleide', [rect(divider + partition, officeEnd + partition, east - divider - partition, lowerSouth - officeEnd - partition), rect(west, lowerSouth, east - west, storeNorth - partition - lowerSouth), rect(storeEast + partition, storeNorth - partition, east - storeEast - partition, parentsSouth - storeNorth + partition)], [3.25, 7.4])]
    floor.furniture = [item('office-desk', 'desk', .35, 1.79, 2, .7, .75), item('office-desk-return', 'table', .35, 2.49, .7, 1.35, .75), item('office-chair', 'chair', 1.35, 2.8, .48, .48, .85), item('office-storage', 'cabinet', 3.1, 1.78, 2.3, .4, 1.0), item('office-south-storage', 'cabinet', 3.6, 5.1, 2.65, .45, 1.1), item('office-plant-west', 'plant', 2.5, 1.83, .4, .4, 1.0), item('office-plant-east', 'plant', 5.75, 1.83, .4, .4, 1.0), item('parents-bed', 'bed', 4.0, 7.85, 1.8, 2, .52, Math.PI), item('parents-north-storage', 'cabinet', 3.6, 5.74, 2.65, .43, 2.2), item('parents-cabinet', 'cabinet', .4, lowerSouth + .04, 1.7, .6, 2.25), item('dressing-low', 'cabinet', .4, storeNorth - partition - .45, 2.45, .45, 1.4), item('store-shelf', 'bookcase', .4, 10.35, 2.4, .35, .55), item('parents-low', 'cabinet', 3.25, 9.4, .6, .45, .7), item('parents-low-east', 'cabinet', 5.95, 9.4, .3, .45, .7)]
  }
  return floor
}